import { chromium } from "playwright-core";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto("http://localhost:5173/contact");
await page.waitForTimeout(3000);
const nameInput = page.locator("input[placeholder*=\"Dr.\"]").first();
await nameInput.fill("Test User");
const emailInput = page.locator("input[type=\"email\"]").first();
await emailInput.fill("test@example.com");
const phoneInput = page.locator("input[placeholder*=\"Phone\"]").first();
await phoneInput.fill("+1234567890");
const orgInput = page.locator("input[placeholder*=\"Health\"]").first();
await orgInput.fill("Test Clinic");
const msgInput = page.locator("textarea").first();
await msgInput.fill("This is a test message");
const sendBtn = page.getByRole("button", { name: /Send Message/i }).first();
await sendBtn.click();
await page.waitForTimeout(5000);
console.log("=== AFTER SUBMIT ===");
console.log((await page.innerText("body")).substring(0, 1000));
const toastCount = await page.locator("[data-sonner-toast], [data-toast], [role=\"status\"]").count();
console.log("Toast count:", toastCount);
const successTexts = await page.locator("text=/success|thank you|message sent|received/i").allTextContents();
console.log("Success texts:", successTexts);
await browser.close();
