import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowRight, Shield, CheckCircle, Lock } from "lucide-react";
import Logo from "@/components/ui/Logo";
import api from "@/lib/api";

export default function TwoFactorVerify() {
  const navigate = useNavigate();
  const location = useLocation();
  const email = (location.state as any)?.email || "";

  const [code, setCode] = useState("");
  const [backupCode, setBackupCode] = useState("");
  const [useBackup, setUseBackup] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!email) navigate("/login");
  }, [email, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const payload: any = { email };
      if (useBackup) {
        payload.backupCode = backupCode;
      } else {
        payload.token = code;
      }
      const { data } = await api.post("/auth/2fa/verify", payload);
      localStorage.setItem("oriveo_token", data.token);
      localStorage.setItem("oriveo_user", JSON.stringify(data.user));
      window.location.href = "/dashboard";
    } catch (err: any) {
      setError(err.response?.data?.message || "Invalid code");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex">
      {/* Left panel — branded */}
      <div className="hidden lg:flex lg:w-1/2 relative overflow-hidden bg-gradient-to-br from-gray-900 via-gray-950 to-black flex-col justify-between p-12">
        <div className="absolute inset-0">
          <div className="absolute top-20 left-10 w-72 h-72 rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute bottom-20 right-10 w-96 h-96 rounded-full bg-emerald-500/5 blur-3xl" />
        </div>
        <div className="relative">
          <Logo size="lg" variant="light" />
        </div>
        <div className="relative space-y-8">
          <h2 className="text-4xl font-bold text-white leading-tight">
            Two-factor<br />authentication
          </h2>
          <p className="text-gray-400 text-lg leading-relaxed max-w-lg">
            Enter the 6-digit code from your authenticator app, or use one of your backup codes.
          </p>
          <div className="space-y-3">
            {[
              "Code generated by your authenticator app",
              "Backup codes work if you lose your device",
              "Each backup code can only be used once",
            ].map((item) => (
              <div key={item} className="flex items-center gap-3">
                <CheckCircle className="h-4 w-4 text-primary shrink-0" />
                <span className="text-sm text-gray-300">{item}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="relative flex items-center gap-2 text-xs text-gray-600">
          <Lock className="h-3 w-3" />
          <span>256-bit TLS encryption in transit</span>
        </div>
      </div>

      {/* Right panel — form */}
      <div className="flex-1 flex flex-col">
        <div className="lg:hidden flex items-center gap-3 p-6 border-b border-gray-100">
          <Logo size="md" variant="dark" />
        </div>

        <div className="flex-1 flex items-center justify-center p-8">
          <div className="w-full max-w-sm space-y-8">
            <div>
              <div className="hidden lg:flex items-center gap-3 cursor-pointer mb-8" onClick={() => navigate("/login")}>
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10">
                  <Shield className="h-5 w-5 text-primary" />
                </div>
                <span className="text-sm font-medium text-gray-500">Back to sign in</span>
              </div>
              <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Enter verification code</h1>
              <p className="text-sm text-gray-500 mt-1.5">
                {useBackup ? "Enter one of your backup codes" : "Enter the 6-digit code from your authenticator app"}
              </p>
            </div>

            {error && (
              <div className="rounded-xl bg-danger-light border border-red-200 px-4 py-3 text-sm text-danger font-medium">
                {error}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-5">
              {useBackup ? (
                <div className="space-y-2">
                  <Label htmlFor="backup" className="text-sm font-medium text-gray-700">Backup code</Label>
                  <Input
                    id="backup"
                    type="text"
                    placeholder="Enter backup code"
                    value={backupCode}
                    onChange={(e) => setBackupCode(e.target.value)}
                    required
                    className="h-11 rounded-xl border-gray-200 focus:border-primary focus:ring-primary font-mono"
                  />
                </div>
              ) : (
                <div className="space-y-2">
                  <Label htmlFor="code" className="text-sm font-medium text-gray-700">Verification code</Label>
                  <Input
                    id="code"
                    type="text"
                    placeholder="000000"
                    value={code}
                    onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                    required
                    maxLength={6}
                    className="h-11 rounded-xl border-gray-200 focus:border-primary focus:ring-primary text-center text-lg tracking-[0.5em] font-mono"
                  />
                </div>
              )}

              <Button type="submit" className="w-full h-11 rounded-xl text-sm font-semibold" disabled={loading}>
                {loading ? (
                  <span className="flex items-center gap-2">
                    <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                    Verifying...
                  </span>
                ) : (
                  <span className="flex items-center gap-2">
                    Verify <ArrowRight className="h-4 w-4" />
                  </span>
                )}
              </Button>
            </form>

            <div className="text-center">
              <button
                onClick={() => { setUseBackup(!useBackup); setError(""); setCode(""); setBackupCode(""); }}
                className="text-xs font-medium text-primary hover:text-primary-dark transition-colors"
              >
                {useBackup ? "Use authenticator code instead" : "Use a backup code instead"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
