export const SUPPORTED_LANGUAGES = {
  en: {
    label: "English",
    deepgram: "flux-general-multi",
    deepgramHint: "en",
    elevenLabsVoiceId: "21m00Tcm4TlvDq8ikWAM",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "English",
  },
  es: {
    label: "Spanish",
    deepgram: "flux-general-multi",
    deepgramHint: "es",
    elevenLabsVoiceId: "g5CIjZEefAph4nQFdHAX",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Spanish",
  },
  fr: {
    label: "French",
    deepgram: "flux-general-multi",
    deepgramHint: "fr",
    elevenLabsVoiceId: "9BWtsMINqrJLrRacOk9x",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "French",
  },
  de: {
    label: "German",
    deepgram: "flux-general-multi",
    deepgramHint: "de",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "German",
  },
  it: {
    label: "Italian",
    deepgram: "flux-general-multi",
    deepgramHint: "it",
    elevenLabsVoiceId: "3yLJw7PABw0M8ADYQ8rD",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Italian",
  },
  pt: {
    label: "Portuguese",
    deepgram: "flux-general-multi",
    deepgramHint: "pt",
    elevenLabsVoiceId: "5Q0t7uMc3F6WSTJAq22p",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Portuguese",
  },
  nl: {
    label: "Dutch",
    deepgram: "flux-general-multi",
    deepgramHint: "nl",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Dutch",
  },
  pl: {
    label: "Polish",
    deepgram: "flux-general-multi",
    deepgramHint: "pl",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Polish",
  },
  ru: {
    label: "Russian",
    deepgram: "flux-general-multi",
    deepgramHint: "ru",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Russian",
  },
  tr: {
    label: "Turkish",
    deepgram: "flux-general-multi",
    deepgramHint: "tr",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Turkish",
  },
  zh: {
    label: "Chinese (Mandarin)",
    deepgram: "flux-general-multi",
    deepgramHint: "zh",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Chinese",
  },
  ja: {
    label: "Japanese",
    deepgram: "flux-general-multi",
    deepgramHint: "ja",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Japanese",
  },
  ko: {
    label: "Korean",
    deepgram: "flux-general-multi",
    deepgramHint: "ko",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Korean",
  },
  ar: {
    label: "Arabic",
    deepgram: "flux-general-multi",
    deepgramHint: "ar",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Arabic",
  },
  hi: {
    label: "Hindi",
    deepgram: "flux-general-multi",
    deepgramHint: "hi",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Hindi",
  },
  bn: {
    label: "Bengali",
    deepgram: "flux-general-multi",
    deepgramHint: "bn",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Bengali",
  },
  ur: {
    label: "Urdu",
    deepgram: "flux-general-multi",
    deepgramHint: "ur",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Urdu",
  },
  vi: {
    label: "Vietnamese",
    deepgram: "flux-general-multi",
    deepgramHint: "vi",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Vietnamese",
  },
  th: {
    label: "Thai",
    deepgram: "flux-general-multi",
    deepgramHint: "th",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Thai",
  },
  sv: {
    label: "Swedish",
    deepgram: "flux-general-multi",
    deepgramHint: "sv",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Swedish",
  },
  da: {
    label: "Danish",
    deepgram: "flux-general-multi",
    deepgramHint: "da",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Danish",
  },
  fi: {
    label: "Finnish",
    deepgram: "flux-general-multi",
    deepgramHint: "fi",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Finnish",
  },
  nb: {
    label: "Norwegian",
    deepgram: "flux-general-multi",
    deepgramHint: "nb",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Norwegian",
  },
  cs: {
    label: "Czech",
    deepgram: "flux-general-multi",
    deepgramHint: "cs",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Czech",
  },
  ro: {
    label: "Romanian",
    deepgram: "flux-general-multi",
    deepgramHint: "ro",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Romanian",
  },
  uk: {
    label: "Ukrainian",
    deepgram: "flux-general-multi",
    deepgramHint: "uk",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Ukrainian",
  },
  el: {
    label: "Greek",
    deepgram: "flux-general-multi",
    deepgramHint: "el",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Greek",
  },
  he: {
    label: "Hebrew",
    deepgram: "flux-general-multi",
    deepgramHint: "he",
    elevenLabsVoiceId: "N2lVS1w4EtoT3dr4eOWO",
    elevenLabsModel: "eleven_turbo_v2_5",
    ttsPrefix: "",
    openaiLanguage: "Hebrew",
  },
};

export const LANGUAGE_LIST = Object.entries(SUPPORTED_LANGUAGES).map(
  ([code, config]) => ({
    code,
    label: config.label,
  })
);

export function getLanguageConfig(code) {
  return SUPPORTED_LANGUAGES[code] || SUPPORTED_LANGUAGES.en;
}

export function detectLanguageFromDeepgram(languages) {
  if (!languages || !languages.length) return null;
  const primary = languages[0];
  for (const [code, cfg] of Object.entries(SUPPORTED_LANGUAGES)) {
    if (cfg.deepgramHint === primary) return code;
  }
  return null;
}
