export const REPORT_TEMPLATES = {
  "general-practice": {
    clinicType: "human",
    label: "General Practice / Family Medicine",
    standard: "SOAP (Subjective, Objective, Assessment, Plan) per American Academy of Family Physicians guidelines",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Patient's main reason for visit in their own words (1-2 sentences)" },
      { id: "hpi", label: "History of Present Illness", description: "Detailed narrative of the current illness using OLDCARTS (Onset, Location, Duration, Character, Aggravating factors, Relieving factors, Timing, Severity)" },
      { id: "pmh", label: "Past Medical History", description: "Chronic conditions, hospitalizations, surgeries, medications, allergies" },
      { id: "ros", label: "Review of Systems", description: "Systematic review: constitutional, HEENT, cardiovascular, respiratory, GI, GU, musculoskeletal, neurological, psychiatric, skin" },
      { id: "vitals", label: "Vital Signs", description: "BP, HR, RR, Temp, O2 sat, BMI" },
      { id: "physicalExam", label: "Physical Examination", description: "Focused exam findings per relevant systems" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "Problem list with ICD-10 codes, differential diagnoses, severity" },
      { id: "plan", label: "Plan", description: "Treatment plan: medications, labs, imaging, referrals, follow-up, patient education" },
    ],
    assessmentScales: [],
    commonIcd10: ["A00-B99", "C00-D49", "E00-E89", "F01-F99", "G00-G99", "I00-I99", "J00-J99", "K00-K95", "M00-M99", "N00-N99", "R00-R99", "Z00-Z99"],
    commonCpt: ["99201-99215", "99381-99397", "90460-90461"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive family medicine SOAP note. Include: chief complaint, HPI using OLDCARTS, relevant PMH, focused ROS, vital signs, physical exam findings, assessment with ICD-10 codes, and a detailed plan. Follow AAFP documentation standards.`,
  },

  "cardiology": {
    clinicType: "human",
    label: "Cardiology",
    standard: "ACC/AHA Clinical Documentation Guidelines — SOAP with focused cardiac examination",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Primary cardiac symptom (chest pain, dyspnea, palpitations, syncope, edema)" },
      { id: "hpi", label: "History of Present Illness", description: "Chest pain: PQRST (Provocation, Quality, Radiation, Severity, Timing). Associated symptoms: SOB, diaphoresis, nausea, palpitations. CCS angina classification" },
      { id: "cardiacHistory", label: "Cardiac History", description: "Prior MI, PCI, CABG, heart failure, arrhythmias, valvular disease, pacemaker/ICD" },
      { id: "riskFactors", label: "Cardiovascular Risk Factors", description: "HTN, DM, dyslipidemia, smoking, family history of premature CAD, obesity, sedentary lifestyle" },
      { id: "medications", label: "Cardiac Medications", description: "Antiplatelets, statins, beta-blockers, ACEi/ARB, diuretics, anticoagulants, antiarrhythmics" },
      { id: "vitals", label: "Vital Signs & Cardiac Measurements", description: "BP (both arms), HR, RR, O2 sat, BMI, waist circumference" },
      { id: "physicalExam", label: "Cardiovascular Examination", description: "JVP, carotid upstroke, precordial palpation, heart sounds (S1, S2, S3, S4, murmurs, rubs, clicks), lung auscultation, peripheral edema, peripheral pulses" },
      { id: "diagnosticTests", label: "Diagnostic Tests", description: "ECG interpretation, echocardiogram findings, stress test results, cardiac enzymes, lipid panel, BNP, Holter monitor, cardiac catheterization" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses: IHD, CHF, arrhythmias, valvular disease. NYHA functional class, CCS angina class, ACC/AHA stage" },
      { id: "plan", label: "Plan", description: "Medication adjustments, interventional procedures, lifestyle modifications, follow-up interval, cardiac rehab referral" },
    ],
    assessmentScales: [
      { id: "nyhaClass", label: "NYHA Functional Class", options: ["I - No limitation", "II - Slight limitation", "III - Marked limitation", "IV - Unable to carry out any physical activity"] },
      { id: "ccsAngina", label: "CCS Angina Classification", options: ["0 - Asymptomatic", "I - Ordinary activity does not cause angina", "II - Slight limitation of ordinary activity", "III - Marked limitation of ordinary activity", "IV - Unable to perform any activity without angina"] },
      { id: "accAhaStage", label: "ACC/AHA Heart Failure Stage", options: ["A - At high risk for HF", "B - Structural heart disease without signs/symptoms", "C - Structural heart disease with prior/current symptoms", "D - Refractory HF requiring specialized interventions"] },
    ],
    commonIcd10: ["I10", "I11.9", "I20.0", "I21.9", "I25.10", "I48.91", "I50.9", "I70.0"],
    commonCpt: ["93000", "93005", "93015", "93306", "93325", "78452"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive cardiology SOAP note following ACC/AHA documentation standards. Include: chief complaint, detailed HPI with PQRST for chest pain, cardiac history, risk factors, medication list, vital signs, focused cardiovascular exam, ECG interpretation and diagnostic test results, assessment with ICD-10 codes and NYHA/CCS classification, and a detailed plan.`,
  },

  "pediatrics": {
    clinicType: "human",
    label: "Pediatrics",
    standard: "AAP Pediatric Documentation Guidelines — SOAP with age-appropriate assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Reason for visit (from parent/guardian for younger children)" },
      { id: "hpi", label: "History of Present Illness", description: "Detailed symptom chronology: onset, fever pattern, feeding, urine output, activity level, sleep" },
      { id: "birthHistory", label: "Birth & Developmental History", description: "Gestational age at birth, birth weight, delivery complications, APGAR scores, neonatal ICU stay" },
      { id: "developmentalMilestones", label: "Developmental Milestones", description: "Gross motor, fine motor, language, social skills per CDC/AAP milestone checklists, M-CHAT for autism screening" },
      { id: "immunizations", label: "Immunization Status", description: "CDC schedule compliance, vaccines given today, next due date" },
      { id: "growth", label: "Growth Parameters", description: "Weight, height/length, head circumference (under 3 years), BMI (over 2 years), percentiles on WHO/CDC growth charts" },
      { id: "vitals", label: "Vital Signs", description: "Age-appropriate normals: HR, RR, BP, Temp, O2 sat" },
      { id: "physicalExam", label: "Physical Examination", description: "Complete exam including growth assessment, developmental screening, vision/hearing screening" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, severity, acute vs chronic conditions" },
      { id: "plan", label: "Plan", description: "Treatment, anticipatory guidance, injury prevention, follow-up, school/work notes, weight-based medication dosing" },
    ],
    assessmentScales: [
      { id: "mchat", label: "M-CHAT-R/F Autism Screening", options: ["Low risk", "Medium risk", "High risk"] },
      { id: "edinburgScale", label: "Edinburgh Postnatal Depression Scale", description: "Score /30" },
    ],
    commonIcd10: ["J00-J06", "J15-J18", "H65-H66", "R50.9", "R11.2", "Z00.129", "Z23"],
    commonCpt: ["99381-99385", "99391-99395", "90460-90461", "96110", "96112"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive pediatric SOAP note following AAP documentation standards. Include: chief complaint, HPI with focus on feeding/hydration/activity, birth history (for infants), developmental milestones per CDC checklists, immunization status with CDC schedule, growth parameters with percentiles, age-appropriate vital signs, detailed physical exam, assessment with ICD-10 codes, and plan with weight-based dosing.`,
  },

  "neurology": {
    clinicType: "human",
    label: "Neurology",
    standard: "AAN Clinical Documentation Guidelines — SOAP with comprehensive neurological exam",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Primary neurological symptom (headache, dizziness, weakness, numbness, seizure, memory loss)" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom onset (sudden vs gradual), progression, frequency, duration, triggers, associated symptoms. For headache: ICHD-3 criteria, migraine vs tension vs cluster" },
      { id: "neurologicHistory", label: "Neurological History", description: "Prior strokes/TIA, seizures, migraines, head trauma, CNS infections, neurodegenerative disease, spinal disorders" },
      { id: "medications", label: "Neurological Medications", description: "Antiepileptics, migraine prophylaxis, anticoagulants, antiparkinsonian, MS therapies" },
      { id: "vitals", label: "Vital Signs", description: "BP, HR, RR, Temp, O2 sat" },
      { id: "neuroExam", label: "Neurological Examination", description: "Mental status (MMSE/MoCA), cranial nerves I-XII, motor (strength 0-5 scale), sensory (light touch, pinprick, proprioception), reflexes (0-4+), coordination (finger-to-nose, heel-to-shin), gait, Romberg" },
      { id: "diagnosticTests", label: "Diagnostic Tests", description: "MRI/CT findings, EEG, EMG/NCV, lumbar puncture results, evoked potentials" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, localization, severity scales (NIHSS, Rankin, MIDAS)" },
      { id: "plan", label: "Plan", description: "Medication management, further testing, referrals, follow-up, driving/work restrictions, seizure precautions" },
    ],
    assessmentScales: [
      { id: "nihss", label: "NIH Stroke Scale", description: "Score /42" },
      { id: "moca", label: "MoCA Score", description: "Score /30 (cutoff 26)" },
      { id: "mmse", label: "MMSE Score", description: "Score /30 (cutoff 24)" },
      { id: "migraineDisability", label: "MIDAS Score", description: "Grade I-IV disability" },
      { id: "rankin", label: "Modified Rankin Scale", description: "0-6 (0=none, 6=death)" },
    ],
    commonIcd10: ["G40.909", "G43.909", "G44.209", "I63.9", "G20", "G35", "G30.9", "R56.9"],
    commonCpt: ["99221-99223", "99231-99233", "95816", "95819", "95907-95913"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive neurology SOAP note following AAN documentation standards. Include: chief complaint, detailed HPI with ICHD-3 criteria for headache, neurological history, medication list, vital signs, complete neurological exam (mental status, cranial nerves, motor/sensory/reflex/coordination/gait), diagnostic test results, assessment with ICD-10 codes and severity scales (NIHSS/MoCA/Rankin), and a detailed plan.`,
  },

  "psychiatry": {
    clinicType: "human",
    label: "Psychiatry / Behavioral Health",
    standard: "APA Practice Guidelines — SOAP with Mental Status Examination and standardized rating scales",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Reason for visit in patient's own words" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom chronology: onset, duration, frequency, severity, precipitating factors, prior episodes. Suicidal/homicidal ideation assessment (C-SSRS)" },
      { id: "psychiatricHistory", label: "Psychiatric History", description: "Prior diagnoses, hospitalizations, treatment history (medications, therapy, ECT/TMS), adherence" },
      { id: "substanceUse", label: "Substance Use History", description: "Alcohol, tobacco, cannabis, stimulants, opioids, other drugs. AUDIT/DAST screening" },
      { id: "socialHistory", label: "Social History", description: "Living situation, occupation, marital status, support system, legal history, trauma history" },
      { id: "medications", label: "Current Medications", description: "Psychotropics: antidepressants, antipsychotics, mood stabilizers, anxiolytics, stimulants. Dosages, adherence, side effects" },
      { id: "mse", label: "Mental Status Examination", description: "Appearance, behavior, attitude, speech, mood, affect, thought process/ content, perceptions (hallucinations/delusions), cognition, insight, judgment" },
      { id: "riskAssessment", label: "Risk Assessment", description: "Suicide risk (C-SSRS), homicide risk, self-harm, impulsivity, access to means" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "DSM-5-TR diagnoses with specifiers, ICD-10 codes, severity (mild/moderate/severe), GAF score" },
      { id: "plan", label: "Plan", description: "Medication adjustments (dose, frequency, monitoring), therapy modality/frequency, crisis safety plan, follow-up interval, labs monitoring" },
    ],
    assessmentScales: [
      { id: "phq9", label: "PHQ-9", description: "Depression severity /27 (5-9 mild, 10-14 moderate, 15-19 moderately severe, 20-27 severe)" },
      { id: "gad7", label: "GAD-7", description: "Anxiety severity /21 (5-9 mild, 10-14 moderate, 15-21 severe)" },
      { id: "cssrs", label: "C-SSRS", description: "Columbia-Suicide Severity Rating Scale — lifetime/recent ideation and behavior" },
      { id: "ymrs", label: "YMRS", description: "Young Mania Rating Scale /60" },
      { id: "audit", label: "AUDIT", description: "Alcohol Use Disorders Identification Test /40" },
    ],
    commonIcd10: ["F32.9", "F33.9", "F41.1", "F41.9", "F31.9", "F20.9", "F43.10", "F90.0", "F42", "F60.3"],
    commonCpt: ["90791", "90792", "90832", "90834", "90837", "90846", "90847", "99212-99215"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive psychiatric SOAP note following APA Practice Guidelines. Include: chief complaint, detailed HPI with C-SSRS suicide risk assessment, psychiatric history, substance use history, social history, current medications with adherence, complete Mental Status Examination, risk assessment, DSM-5-TR diagnoses with ICD-10 codes and PHQ-9/GAD-7 scores, and a detailed treatment plan with medication management and therapy recommendations.`,
  },

  "dermatology": {
    clinicType: "human",
    label: "Dermatology",
    standard: "AAD Clinical Documentation Guidelines — SOAP with lesion description and ABCDE criteria",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Skin concern: rash, lesion, mole, itching, hair loss, nail change" },
      { id: "hpi", label: "History of Present Illness", description: "Onset, duration, progression, associated symptoms (pruritus, pain, bleeding), aggravating/relieving factors, prior treatment" },
      { id: "skinExam", label: "Skin Examination", description: "Lesion description: type (macule, papule, plaque, nodule, vesicle, bulla, pustule, ulcer), distribution, configuration, color, size, border. ABCD rule for pigmented lesions. TBSA for rashes. Dermoscopic findings" },
      { id: "photoDocumentation", label: "Photo Documentation", description: "Clinical photos taken, body map location, serial comparison" },
      { id: "biopsy", label: "Biopsy Results", description: "Site, type (shave, punch, excision), histopathology findings, margins" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, differential diagnoses, severity (BSA, PGA, IGA scores)" },
      { id: "plan", label: "Plan", description: "Topical/systemic medications, phototherapy, surgical plan (excision, MOHS), wound care, sun protection counseling, follow-up" },
    ],
    assessmentScales: [
      { id: "pasi", label: "PASI Score", description: "Psoriasis Area and Severity Index /72" },
      { id: "eczemaArea", label: "EASI Score", description: "Eczema Area and Severity Index" },
      { id: "acneGrade", label: "Acne Grading", description: "I (mild) to IV (severe cystic)" },
    ],
    commonIcd10: ["L40.9", "L20.9", "L70.0", "C44.9", "D22.9", "D23.9", "L03.011", "B07.9", "L82.1", "L85.3"],
    commonCpt: ["11100", "11101", "11300-11313", "11400-11446", "11600-11646", "96900-96904"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive dermatology SOAP note following AAD documentation standards. Include: chief complaint, detailed HPI of skin condition, complete skin exam with lesion description (type, distribution, morphology, ABCD rule), photo documentation status, biopsy results if applicable, assessment with ICD-10 codes and severity scores (PASI/EASI), and a detailed treatment plan.`,
  },

  "therapy": {
    clinicType: "human",
    label: "Physical / Occupational / Speech Therapy",
    standard: "APTA/OTA/ASHA Clinical Documentation — SOAP with functional assessment and 8-minute billing rule",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Functional limitation or rehabilitation need" },
      { id: "hpi", label: "History of Present Illness", description: "Injury/condition mechanism, onset, prior therapy, surgical history, functional limitations at home/work" },
      { id: "functionalAssessment", label: "Functional Assessment", description: "Current functional status: mobility, ADLs, IADLs, work capacity, recreational activities. FIM/CMS-AT score" },
      { id: "objectiveMeasures", label: "Objective Measures", description: "Range of motion (goniometry), manual muscle testing (0-5 scale), sensation, coordination, balance (Berg), gait analysis, pain scale (0-10)" },
      { id: "specialTests", label: "Special Tests", description: "Orthopedic special tests per region (Lachman, Neer, Hawkins, etc.), functional performance tests (Timed Up and Go, 6-min walk)" },
      { id: "assessment", label: "Assessment & Plan", description: "ICD-10 coded diagnoses, prognosis, rehab potential, short/long-term goals (SMART format), G-Code functional limitation reporting" },
      { id: "treatment", label: "Treatment Provided", description: "Therapeutic exercise, manual therapy, neuromuscular re-education, modalities, ADL training. Timed units billed (8-minute rule)" },
      { id: "plan", label: "Plan for Next Visit", description: "Home exercise program, frequency/duration of therapy, re-evaluation date, discharge criteria" },
    ],
    assessmentScales: [
      { id: "bergBalance", label: "Berg Balance Scale", description: "/56 (<45 fall risk)" },
      { id: "tinettiGait", label: "Tinetti Gait & Balance", description: "/28 for gait, /16 for balance" },
      { id: "fim", label: "FIM Score", description: "Functional Independence Measure /126" },
      { id: "painScale", label: "Pain Scale (0-10)", description: "Numeric Pain Rating Scale" },
    ],
    commonIcd10: ["M25.50", "M54.5", "M54.2", "S83.2", "S93.4", "M75.1", "G20", "Z50.0-Z50.9", "Z51.89"],
    commonCpt: ["97110", "97112", "97116", "97140", "97530", "97535", "97161-97164", "97750"],
    billingCodeSet: "timed-units",
    aiPrompt: `Generate a comprehensive therapy SOAP note following APTA/ASHA documentation standards. Include: chief complaint, functional limitations, objective measurements (ROM, MMT, Berg balance, pain scale), special test results, assessment with rehab prognosis and SMART goals, treatment provided with timed units (8-minute rule), and a detailed home exercise and follow-up plan.`,
  },

  "gastroenterology": {
    clinicType: "human",
    label: "Gastroenterology",
    standard: "AGA Clinical Documentation — SOAP with endoscopic and pathologic correlation",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "GI symptom: abdominal pain, dysphagia, nausea/vomiting, diarrhea, constipation, GI bleeding, jaundice" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom location, quality, timing, aggravating/relieving factors, associated symptoms (weight loss, appetite change, night symptoms). Rome IV criteria for functional disorders" },
      { id: "giHistory", label: "GI History", description: "Prior endoscopy/colonoscopy, IBD history, hepatitis, pancreatitis, gallbladder disease, GI surgeries, family history of GI cancers" },
      { id: "endoscopy", label: "Endoscopic Findings", description: "EGD/colonoscopy report: indication, preparation quality (Boston Bowel Prep Scale), findings, biopsies taken, interventions performed" },
      { id: "pathology", label: "Pathology Results", description: "Biopsy results: H. pylori, celiac, dysplasia, IBD activity grade" },
      { id: "imaging", label: "Imaging", description: "CT/MRI abdomen, HIDA scan, MRCP, abdominal ultrasound" },
      { id: "labs", label: "Laboratory", description: "LFTs, amylase/lipase, CBC, iron studies, celiac panel, H. pylori testing" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, disease activity (Mayo score for UC, CDAI for Crohn's), Montreal classification for IBD" },
      { id: "plan", label: "Plan", description: "Medication management (PPI, biologics, immunosuppressants), screening interval, surveillance colonoscopy timing, diet/nutrition counseling" },
    ],
    assessmentScales: [
      { id: "mayoScore", label: "Mayo Score (UC)", description: "0-12 (remission 0-2, mild 3-5, moderate 6-10, severe 11-12)" },
      { id: "cdai", label: "CDAI (Crohn's)", description: "<150 remission, 150-220 mild, 221-450 moderate, >450 severe" },
      { id: "bostonPrep", label: "Boston Bowel Prep Scale", description: "0-9 (each segment 0-3), adequate >=6" },
    ],
    commonIcd10: ["K21.9", "K50.90", "K51.90", "K57.30", "K59.00", "K80.20", "K85.90", "B96.81", "K29.70", "K31.89"],
    commonCpt: ["43235", "43239", "45378", "45380", "45385", "91034", "91035", "91037"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive gastroenterology SOAP note following AGA documentation standards. Include: chief complaint, detailed HPI with Rome IV criteria, GI history including prior procedures, endoscopic findings with Boston Bowel Prep Scale, pathology results, relevant imaging and labs, assessment with ICD-10 codes and disease activity scores (Mayo/CDAI), and a detailed treatment and surveillance plan.`,
  },

  "endocrinology": {
    clinicType: "human",
    label: "Endocrinology",
    standard: "AACE/ACE Clinical Practice Guidelines — SOAP with metabolic panel and hormone assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Endocrine concern: diabetes control, thyroid dysfunction, osteoporosis, adrenal/pituitary issues" },
      { id: "hpi", label: "History of Present Illness", description: "Diabetes: glycemic control, hypoglycemic episodes, DKA history. Thyroid: energy level, weight changes, temperature tolerance. Bone health: fractures, falls" },
      { id: "diabetesHistory", label: "Diabetes History", description: "Type, duration, insulin regimen (basal/bolus), CGM data, hypoglycemia unawareness, complications (retinopathy, nephropathy, neuropathy)" },
      { id: "labs", label: "Laboratory Data", description: "HbA1c, FPG, lipid panel, TSH/FT4, calcium/vitamin D, PTH, cortisol, testosterone/estrogen, CGM time-in-range" },
      { id: "complications", label: "Complications Screening", description: "Foot exam (monofilament, pulses), dilated eye exam, urine albumin, GFR" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, diabetes type/control (AACE glycemic control algorithm), thyroid status, bone density T-score" },
      { id: "plan", label: "Plan", description: "Medication adjustments (insulin titration, oral hypoglycemics, thyroid hormone, bisphosphonates), monitoring frequency, screening schedule" },
    ],
    assessmentScales: [
      { id: "hba1cGoal", label: "HbA1c Goal", options: ["<7.0% - most adults", "<7.5% - some adults", "<8.0% - frail/complex", "Individualized"] },
      { id: "timeInRange", label: "CGM Time-in-Range", description: "TIR 70-180 mg/dL: >70% target, <25% above, <4% below" },
      { id: "osteoporosisTScore", label: "Bone Density T-Score", description: "-1.0+ normal, -1.0 to -2.5 osteopenia, <=2.5 osteoporosis" },
    ],
    commonIcd10: ["E11.9", "E10.9", "E03.9", "E05.90", "M81.0", "E28.9", "E29.1", "E27.1", "E24.9", "E88.81"],
    commonCpt: ["83036", "84443", "84439", "80061", "82306", "87070", "77080", "77085"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive endocrinology SOAP note following AACE/ACE guidelines. Include: chief complaint, glycemic control history with CGM data, diabetes history and complications, comprehensive lab data (HbA1c, thyroid panel, bone markers), complications screening results, assessment with ICD-10 codes and glycemic targets, and a detailed medication management plan.`,
  },

  "oncology": {
    clinicType: "human",
    label: "Oncology",
    standard: "NCCN Clinical Practice Guidelines — SOAP with staging per AJCC TNM classification",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Cancer-related concern: treatment side effects, new symptoms, follow-up" },
      { id: "hpi", label: "History of Present Illness", description: "Cancer diagnosis, symptoms (pain, fatigue, weight loss, fever), treatment tolerance, performance status" },
      { id: "cancerHistory", label: "Cancer History", description: "Primary site, histology, grade, stage (TNM), biomarkers (ER/PR, HER2, EGFR, KRAS, etc.), date of diagnosis" },
      { id: "treatmentHistory", label: "Treatment History", description: "Surgery (date, type, margins), chemotherapy (regimen, cycles, cumulative dose), radiation (field, total dose, fractions), immunotherapy, targeted therapy, clinical trials" },
      { id: "currentRegimen", label: "Current Treatment Regimen", description: "Drug names, doses, schedule, cycle number, dose modifications, next treatment date" },
      { id: "toxicity", label: "Treatment Toxicity", description: "CTCAE v5 grading for each adverse event: hematologic, GI, dermatologic, neurologic, cardiac" },
      { id: "imaging", label: "Imaging & Response Assessment", description: "RECIST 1.1 criteria: target lesions, response (CR, PR, SD, PD), new lesions" },
      { id: "labs", label: "Laboratory", description: "CBC with differential, CMP, tumor markers, therapeutic drug monitoring" },
      { id: "assessment", label: "Assessment & Plan", description: "ICD-10 coded diagnoses, disease status (active surveillance, active treatment, palliative, survivorship), ECOG performance status, next cycle plan" },
    ],
    assessmentScales: [
      { id: "ecog", label: "ECOG Performance Status", options: ["0 - Fully active", "1 - Restricted in strenuous activity", "2 - Ambulatory, unable to work", "3 - Limited self-care", "4 - Completely disabled", "5 - Dead"] },
      { id: "recist", label: "RECIST 1.1 Response", options: ["CR - Complete Response", "PR - Partial Response", "SD - Stable Disease", "PD - Progressive Disease"] },
    ],
    commonIcd10: ["C50.9", "C61", "C34.90", "C18.9", "C25.9", "C56.9", "C64.9", "C80.1", "C91.10", "Z51.11", "Z51.0"],
    commonCpt: ["99212-99215", "96401-96425", "96360-96379", "77014", "74177", "71260"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive oncology SOAP note following NCCN guidelines. Include: chief complaint, detailed HPI with performance status, complete cancer history (site, histology, TNM stage, biomarkers), full treatment history (surgery, chemo, radiation), current regimen with doses and cycle, CTCAE v5 toxicity grading, imaging response per RECIST 1.1, relevant labs, assessment with ICD-10 codes and ECOG status, and a detailed treatment plan.`,
  },

  "rheumatology": {
    clinicType: "human",
    label: "Rheumatology",
    standard: "ACR/EULAR Classification Criteria — SOAP with disease activity assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Joint pain, swelling, stiffness, fatigue, rash, organ involvement" },
      { id: "hpi", label: "History of Present Illness", description: "Joint distribution (symmetrical/asymmetrical, small/large, axial/peripheral), duration of morning stiffness, inflammatory vs mechanical pain pattern" },
      { id: "jointExam", label: "Joint Examination", description: "Tender joint count (TJC 28/68), swollen joint count (SJC 28/66), DAS28 score, deformity, ROM" },
      { id: "extraarticular", label: "Extra-Articular Manifestations", description: "Skin (psoriasis, nodules, malar rash), ocular (scleritis, uveitis), pulmonary, cardiac, renal, hematologic" },
      { id: "labs", label: "Laboratory", description: "RF, CCP, ANA, ENA panel, dsDNA, CRP, ESR, complement C3/C4, uric acid, HLA-B27" },
      { id: "imaging", label: "Imaging", description: "X-ray (joint space narrowing, erosions, chondrocalcinosis), ultrasound (synovitis, power Doppler), MRI" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, disease activity (DAS28, CDAI, SDAI, BASDAI), ACR/EULAR classification criteria met, damage assessment" },
      { id: "plan", label: "Plan", description: "DMARD therapy (conventional, biologic, targeted synthetic), NSAIDs, corticosteroids, monitoring labs, vaccination status" },
    ],
    assessmentScales: [
      { id: "das28", label: "DAS28 (Disease Activity Score 28)", description: "<2.6 remission, 2.6-3.2 low, 3.2-5.1 moderate, >5.1 high" },
      { id: "basdai", label: "BASDAI (Ankylosing Spondylitis)", description: "0-10, <4 low disease activity" },
      { id: "scleroderma", label: "Modified Rodnan Skin Score", description: "0-51 skin thickness" },
    ],
    commonIcd10: ["M05.9", "M06.9", "M32.9", "M07.90", "M10.00", "M45.9", "M35.00", "M33.20", "M30.1"],
    commonCpt: ["99212-99215", "36400-36430", "80048-80076", "86140", "86225-86235"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive rheumatology SOAP note following ACR/EULAR guidelines. Include: chief complaint, detailed HPI with inflammatory vs mechanical pain pattern, complete joint exam with TJC/SJC counts and DAS28, extra-articular manifestations, relevant labs (RF, CCP, ANA, CRP, ESR), imaging findings, assessment with ICD-10 codes and disease activity scores (DAS28/CDAI/BASDAI), and a detailed treatment plan including DMARD therapy.`,
  },

  "nephrology": {
    clinicType: "human",
    label: "Nephrology",
    standard: "KDIGO Clinical Practice Guidelines — SOAP with renal function and dialysis assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Renal concern: edema, hypertension, uremic symptoms, dialysis access issue" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom progression, volume status, dietary compliance, medication adherence, intercurrent illness" },
      { id: "renalHistory", label: "Renal History", description: "CKD etiology, duration, prior biopsy, transplant history, dialysis vintage and modality" },
      { id: "dialysis", label: "Dialysis Data", description: "Modality (HD/PD), access type (AVF/AVG/catheter/PD catheter), Kt/V, URR, ultrafiltration, weight gain, adequacy" },
      { id: "labs", label: "Laboratory", description: "GFR (eGFR, creatinine, BUN), electrolytes, calcium/phosphate/PTH, bicarbonate, anemia (Hb, ferritin, TSAT)" },
      { id: "volumeStatus", label: "Volume Status Assessment", description: "JVP, edema, lung auscultation, weight trends, BP, orthostatic changes" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, CKD stage (G1-G5), KDIGO classification (G+A+C categories), dialysis adequacy" },
      { id: "boneMetabolism", label: "CKD-MBD Assessment", description: "Calcium, phosphate, PTH, alkaline phosphatase, vitamin D management" },
      { id: "anemia", label: "Anemia Management", description: "Hb target, iron stores, ESA dose, iron supplementation" },
      { id: "plan", label: "Plan", description: "Medication adjustments, dialysis prescription modification, access monitoring, transplant referral status" },
    ],
    assessmentScales: [
      { id: "ckdStage", label: "CKD Stage (GFR)", options: ["G1: >=90", "G2: 60-89", "G3a: 45-59", "G3b: 30-44", "G4: 15-29", "G5: <15"] },
      { id: "albuminuria", label: "Albuminuria Category", options: ["A1: <30 mg/g", "A2: 30-300 mg/g", "A3: >300 mg/g"] },
    ],
    commonIcd10: ["N18.3", "N18.4", "N18.5", "N18.6", "N19", "I12.9", "N17.9", "E11.22", "Z49.01", "Z49.31"],
    commonCpt: ["90960", "90961", "90962", "90966", "90970", "80048-80076", "82040", "82310"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive nephrology SOAP note following KDIGO guidelines. Include: chief complaint, volume status assessment, renal history with CKD etiology, dialysis data (Kt/V, access, ultrafiltration), comprehensive lab data (GFR, electrolytes, bone panel, anemia labs), CKD-MBD assessment, anemia management status, assessment with ICD-10 codes and KDIGO stage (G+A+C), and a detailed dialysis and medication plan.`,
  },

  "pulmonology": {
    clinicType: "human",
    label: "Pulmonology",
    standard: "ATS/ERS Clinical Documentation — SOAP with pulmonary function interpretation",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Respiratory symptom: dyspnea, cough, wheezing, hemoptysis, sleep apnea" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom onset (acute vs chronic), severity (mMRC dyspnea scale), triggers, sputum production/character, hemoptysis, night symptoms, exercise tolerance" },
      { id: "pulmHistory", label: "Pulmonary History", description: "Asthma, COPD, ILD, OSA, PE, lung cancer, TB, prior PFTs, hospitalizations, intubations" },
      { id: "socialHistory", label: "Social & Occupational History", description: "Smoking history (pack-years), occupational exposures (asbestos, silica, coal), environmental exposures" },
      { id: "vitals", label: "Vital Signs", description: "RR, O2 sat (rest, exertion, nighttime), spirometry: FEV1, FVC, FEV1/FVC, PEF" },
      { id: "pft", label: "Pulmonary Function Tests", description: "Spirometry, lung volumes (TLC, RV), DLCO, bronchodilator response, bronchoprovocation, ATS/ERS interpretation" },
      { id: "imaging", label: "Imaging", description: "Chest X-ray, CT chest (HRCT for ILD, CT angio for PE), PET-CT for lung cancer" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, GOLD stage for COPD, GINA step for asthma, mMRC dyspnea class, CAT score" },
      { id: "plan", label: "Plan", description: "Inhaler therapy adjustments, pulmonary rehab, oxygen therapy, sleep study, smoking cessation, vaccination" },
    ],
    assessmentScales: [
      { id: "mmrc", label: "mMRC Dyspnea Scale", options: ["0 - Only on strenuous exercise", "1 - Short of breath hurrying", "2 - Walks slower than peers", "3 - Stops after 100m", "4 - Too breathless to leave house"] },
      { id: "cat", label: "CAT Score (COPD)", description: "0-40 quality of life impact" },
      { id: "goldStage", label: "GOLD Stage", options: ["GOLD 1 - Mild", "GOLD 2 - Moderate", "GOLD 3 - Severe", "GOLD 4 - Very Severe"] },
    ],
    commonIcd10: ["J44.9", "J45.909", "J84.9", "J96.00", "J90", "G47.33", "I26.09", "R04.2", "J43.9", "J98.4"],
    commonCpt: ["94010", "94060", "94070", "94200", "94375", "94726", "94727", "94729", "71250-71275"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive pulmonology SOAP note following ATS/ERS guidelines. Include: chief complaint, detailed HPI with mMRC dyspnea scale, pulmonary history, smoking/social history, vital signs and O2 sat, PFT interpretation (spirometry, lung volumes, DLCO with ATS/ERS pattern), imaging findings, assessment with ICD-10 codes and GOLD/GINA staging, and a detailed treatment plan.`,
  },

  "ophthalmology": {
    clinicType: "human",
    label: "Ophthalmology",
    standard: "AAO Preferred Practice Patterns — SOAP with comprehensive ophthalmic examination",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Vision change, eye pain, redness, flashing lights/floaters, discharge" },
      { id: "hpi", label: "History of Present Illness", description: "Onset, duration, laterality, severity, associated symptoms, aggravating/relieving factors" },
      { id: "eyeExam", label: "Ophthalmic Examination", description: "Visual acuity (Snellen), refractive error, pupillary exam (RAPD), ocular motility/alignment, visual fields (confrontation)" },
      { id: "slitLamp", label: "Slit Lamp Examination", description: "Lids/lashes, conjunctiva/sclera, cornea (staining, edema, keratic precipitates), anterior chamber (cell/flare), iris, lens (cataract grade)" },
      { id: "fundoscopy", label: "Funduscopic Examination", description: "Vitreous, optic disc (CD ratio, color, margins), macula, vessels, periphery. Diabetic retinopathy stage, AMD classification" },
      { id: "diagnosticTests", label: "Diagnostic Tests", description: "IOP (Goldmann tonometry), OCT (macular thickness, RNFL), visual fields (Humphrey), corneal topography/pachymetry, fluorescein angiography" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, laterality, severity, staging" },
      { id: "plan", label: "Plan", description: "Medical therapy (eyedrops, oral), laser procedures, surgical plan (cataract, glaucoma, retinal), follow-up interval" },
    ],
    assessmentScales: [
      { id: "visualAcuity", label: "Visual Acuity", description: "Snellen fraction (20/20 to 20/400)" },
      { id: "drStage", label: "Diabetic Retinopathy Stage", options: ["NPDR mild", "NPDR moderate", "NPDR severe", "PDR"] },
      { id: "amdStage", label: "AMD Stage", options: ["None", "Early", "Intermediate", "Advanced - Dry", "Advanced - Wet"] },
      { id: "cataractGrade", label: "Cataract Grade", options: ["1 - Mild", "2 - Moderate", "3 - Advanced", "4 - Hypermature"] },
    ],
    commonIcd10: ["H25.9", "H40.9", "H35.30", "E11.39", "H04.123", "H16.9", "H01.00", "H10.9", "H02.1", "Z96.1"],
    commonCpt: ["99201-99215", "92002-92014", "92081-92083", "92133-92134", "92250", "76514-76519"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive ophthalmology SOAP note following AAO Preferred Practice Patterns. Include: chief complaint, detailed HPI, complete ophthalmic exam (visual acuity, pupils, motility), slit lamp findings, funduscopic exam with DR/AMD staging, IOP, diagnostic test results (OCT, visual fields), assessment with ICD-10 codes and laterality, and a detailed treatment and follow-up plan.`,
  },

  "ent": {
    clinicType: "human",
    label: "ENT / Otolaryngology",
    standard: "AAO-HNS Clinical Practice Guidelines — SOAP with focused head and neck examination",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Ear, nose, throat, or neck concern: hearing loss, tinnitus, vertigo, nasal obstruction, sinus pain, sore throat, hoarseness, neck mass" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom chronology, laterality, severity, associated symptoms, aggravating/relieving factors, prior treatment" },
      { id: "entExam", label: "ENT Examination", description: "Otoscopy (TM appearance, mobility), nasal endoscopy (septum, turbinates, polyps, sinus drainage), oral cavity/pharynx (tonsils, palate, mucosa), laryngoscopy (vocal cords, lesions), neck palpation (thyroid, lymph nodes)" },
      { id: "hearingTest", label: "Hearing Assessment", description: "Audiometry (pure tone, speech), tympanometry, tuning fork tests (Rinne, Weber)" },
      { id: "imaging", label: "Imaging", description: "CT sinuses, MRI temporal bone, CT neck, ultrasound thyroid" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 coded diagnoses, laterality, severity" },
      { id: "plan", label: "Plan", description: "Medical therapy (antibiotics, steroids, antihistamines), surgical options (tympanoplasty, septoplasty, tonsillectomy, sinus surgery), hearing aids, follow-up" },
    ],
    assessmentScales: [
      { id: "hearingLoss", label: "Hearing Loss Grade", options: ["Normal (<25 dB)", "Mild (26-40 dB)", "Moderate (41-55 dB)", "Moderate-severe (56-70 dB)", "Severe (71-90 dB)", "Profound (>90 dB)"] },
    ],
    commonIcd10: ["H66.91", "H65.9", "J32.9", "J35.0", "J35.1", "J01.9", "R04.0", "R42", "E04.9", "R91.1"],
    commonCpt: ["99201-99215", "92550-92557", "92567", "31231-31237", "69420-69436", "42820-42826"],
    billingCodeSet: "cpt",
    aiPrompt: `Generate a comprehensive ENT SOAP note following AAO-HNS guidelines. Include: chief complaint, detailed HPI, complete ENT exam (otoscopy, nasal endoscopy, oral exam, laryngoscopy, neck palpation), hearing assessment (audiometry, tympanometry), imaging findings, assessment with ICD-10 codes and laterality, and a detailed medical/surgical treatment plan.`,
  },

  "general-dentistry": {
    clinicType: "dental",
    label: "General Dentistry",
    standard: "ADA Clinical Documentation Guidelines — SOAP with periodontal charting and caries assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Dental concern: tooth pain, sensitivity, broken tooth, bleeding gums, esthetics, routine exam" },
      { id: "hpi", label: "History of Present Illness", description: "Pain history: onset, duration, triggers (hot/cold/sweet/biting), spontaneous pain, swelling, prior treatment" },
      { id: "dentalHistory", label: "Dental History", description: "Last dental visit, frequency of care, prior restorations, extractions, root canals, periodontal treatment, orthodontic history" },
      { id: "medicalHistory", label: "Medical History", description: "Medications (anticoagulants, bisphosphonates), allergies, pregnancy, diabetes, cardiac conditions, ASA classification" },
      { id: "intraoralExam", label: "Intraoral Examination", description: "ADA tooth numbering, caries chart (D1-D4), restorations present, missing teeth, occlusion, oral mucosa, tongue, floor of mouth" },
      { id: "periodontalChart", label: "Periodontal Charting", description: "Probing depths (6 sites/tooth), bleeding on probing, gingival recession, CAL, furcation involvement, mobility (0-3), plaque index" },
      { id: "radiographs", label: "Radiographic Findings", description: "BWX, PA, panoramic, CBCT. Caries depth, periapical pathology, bone level, impacted teeth, sinus findings" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10-CM dental codes, caries risk assessment (ADA CRA), periodontal diagnosis (staging/grading), treatment needs" },
      { id: "plan", label: "Treatment Plan", description: "Restorative (composite, crown, bridge), endodontic (RCT), surgical (extraction, implant), periodontal (SRP, surgery), preventive (sealant, fluoride), prosthetic (denture, partial)" },
    ],
    assessmentScales: [
      { id: "cariesRisk", label: "ADA Caries Risk Assessment", options: ["Low", "Moderate", "High"] },
      { id: "perioStage", label: "Periodontal Staging", options: ["Stage I - Initial", "Stage II - Moderate", "Stage III - Severe with potential for tooth loss", "Stage IV - Advanced with extensive tooth loss"] },
      { id: "asaClass", label: "ASA Physical Status", options: ["ASA I - Normal healthy", "ASA II - Mild systemic disease", "ASA III - Severe systemic disease", "ASA IV - Severe disease constant threat"] },
    ],
    commonIcd10: ["K02.9", "K04.7", "K05.6", "K03.81", "K00.6", "K01.1", "S02.5", "K12.3", "K06.8", "Z01.21"],
    commonCpt: "CDT D0120-D9999",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive general dentistry SOAP note following ADA documentation standards. Include: chief complaint, HPI with pain history, dental and medical history, complete intraoral exam with ADA tooth numbering, 6-point periodontal charting, radiographic findings, assessment with ICD-10-CM codes and caries risk/periodontal staging (ADA classification), and a comprehensive treatment plan with CDT codes.`,
  },

  "orthodontics": {
    clinicType: "dental",
    label: "Orthodontics",
    standard: "AAO Clinical Documentation — Cephalometric analysis and treatment progress assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Malocclusion concern: crowding, spacing, overjet, overbite, crossbite, smile esthetics" },
      { id: "hpi", label: "History of Present Illness", description: "Orthodontic history: prior treatment, extractions, growth modification, compliance with elastics/headgear" },
      { id: "clinicalExam", label: "Clinical Examination", description: "Extraoral: facial profile (convex/straight/concave), smile line, lip competence. Intraoral: molar classification (Angle Class I/II/III), canine relationship, overjet, overbite, crossbite, crowding/spacing (mm), arch form" },
      { id: "records", label: "Diagnostic Records", description: "Cephalometric analysis (SNA, SNB, ANB, FMA, IMPA, incisor angulation), panoramic radiograph, study models/digital scans, photos" },
      { id: "applianceCheck", label: "Appliance Assessment", description: "Wire type/size (e.g., 0.019x0.025 SS), bracket positioning, elastics pattern/ wear, headgear/Herbst compliance, TADs, aligner stage" },
      { id: "progress", label: "Treatment Progress", description: "Movement achieved vs planned, remaining space closure, interarch coordination, PAR score change, phase of treatment" },
      { id: "assessment", label: "Assessment & Plan", description: "ICD-10 codes for malocclusion, treatment stage, next adjustments, estimated remaining duration" },
    ],
    assessmentScales: [
      { id: "angleClass", label: "Angle Classification", options: ["Class I - Neutrocclusion", "Class II - Distoclusion", "Class III - Mesioclusion"] },
      { id: "parScore", label: "PAR Index", description: "Peer Assessment Rating score (0-100), <10 excellent improvement" },
    ],
    commonIcd10: ["M26.29", "M26.10", "M26.4", "M26.3", "M26.21", "M26.22"],
    commonCpt: "CDT D8070-D8090, D8210-D8220, D8670, D8680",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive orthodontic SOAP note following AAO documentation standards. Include: chief complaint, malocclusion history, extraoral/intraoral exam with Angle classification and measurements, cephalometric analysis (SNA/SNB/ANB/FMA), study model assessment, current appliance details (wire size/type, elastics), treatment progress and PAR score change, assessment with ICD-10 codes, and a detailed adjustment plan.`,
  },

  "endodontics": {
    clinicType: "dental",
    label: "Endodontics",
    standard: "AAE Case Difficulty Assessment — SOAP with root canal treatment documentation",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Tooth-specific pain: spontaneous pain, thermal sensitivity, percussion sensitivity, swelling" },
      { id: "hpi", label: "History of Present Illness", description: "Pain history: onset, duration, intensity (0-10), triggers, referred pain, prior endodontic treatment attempts" },
      { id: "diagnosticTesting", label: "Diagnostic Testing", description: "Cold/heat test, EPT (electric pulp test), percussion, palpation, mobility, periodontal probing, transillumination, tooth number (ADA)" },
      { id: "radiographs", label: "Radiographic Assessment", description: "PA and BWX: caries depth, pulp chamber size, root morphology (number of canals), periapical pathology (CBCT if indicated), previous RCT quality" },
      { id: "accessCavity", label: "Access & Canal Findings", description: "Access preparation, number of canals located, working length measurements, patency, calcifications, perforations" },
      { id: "instrumentation", label: "Instrumentation & Obturation", description: "Final file size, taper, irrigation protocol (NaOCl, EDTA, chlorhexidine), intracanal medicament, obturation technique and material, cone fit" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 codes, pulpal diagnosis (normal, reversible pulpitis, irreversible pulpitis, necrotic), periapical diagnosis (normal, acute/chronic apical periodontitis, abscess), AAE difficulty level" },
      { id: "postOp", label: "Post-Operative Care", description: "Pain management, crown recommendation, follow-up interval, final restoration plan" },
    ],
    assessmentScales: [
      { id: "aaeDifficulty", label: "AAE Case Difficulty", options: ["Minimal", "Moderate", "High"] },
      { id: "pulpalDiagnosis", label: "Pulpal Diagnosis", options: ["Normal", "Reversible Pulpitis", "Irreversible Pulpitis", "Necrosis", "Previously Treated"] },
      { id: "periapicalDiagnosis", label: "Periapical Diagnosis", options: ["Normal", "Symptomatic Apical Periodontitis", "Asymptomatic Apical Periodontitis", "Chronic Apical Abscess", "Acute Apical Abscess", "Condensing Osteitis"] },
    ],
    commonIcd10: ["K04.01", "K04.02", "K04.4", "K04.5", "K04.7", "K04.8", "K04.9", "K03.81"],
    commonCpt: "CDT D3310-D3349",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive endodontic SOAP note following AAE documentation standards. Include: chief complaint, detailed pain history, diagnostic testing results (cold/EPT/percussion), pre-op radiograph findings, access and canal findings (number of canals, working lengths, patency), instrumentation and irrigation protocol, obturation details, assessment with ICD-10 codes and pulpal/periapical diagnoses and AAE difficulty level, and post-operative instructions.`,
  },

  "periodontics": {
    clinicType: "dental",
    label: "Periodontics",
    standard: "AAP Periodontal Disease Classification — SOAP with comprehensive periodontal assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Gum concern: bleeding, recession, mobility, pain, halitosis, esthetics" },
      { id: "hpi", label: "History of Present Illness", description: "Duration of gum issues, bleeding pattern, prior periodontal treatment (SRP, surgery, maintenance interval), compliance" },
      { id: "riskFactors", label: "Risk Factor Assessment", description: "Smoking status, diabetes (HbA1c), genetics, medications (CCBs, phenytoin, cyclosporine), stress, occlusal trauma" },
      { id: "fullPerioExam", label: "Comprehensive Periodontal Examination", description: "Full-mouth probing (6 sites/tooth), BOP%, recession, CAL, furcation (Hamp class I-III), mobility (Miller 0-3), mucogingival assessment, plaque/index, occlusal trauma" },
      { id: "radiographs", label: "Radiographic Assessment", description: "Bone levels (CEJ to bone crest), vertical/horizontal bone loss, furcation radiolucency, calculus, perio-end lesions, CBCT for implant planning" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 codes, AAP 2018 classification: periodontal health, gingivitis, periodontitis (staging I-IV, grading A-C), peri-implant disease, mucogingival conditions" },
      { id: "plan", label: "Treatment Plan", description: "Phase I (SRP, OHI, risk factor control), Phase II (re-evaluation), Phase III (surgery: pocket reduction, regeneration, grafting, crown lengthening), Phase IV (maintenance period)" },
    ],
    assessmentScales: [
      { id: "perioStage", label: "AAP Periodontitis Stage", options: ["Stage I - Initial", "Stage II - Moderate", "Stage III - Severe with potential for tooth loss", "Stage IV - Advanced with extensive tooth loss"] },
      { id: "perioGrade", label: "AAP Periodontitis Grade", options: ["Grade A - Slow progression", "Grade B - Moderate progression", "Grade C - Rapid progression"] },
      { id: "furcation", label: "Furcation Involvement (Hamp)", options: ["Class I", "Class II", "Class III"] },
    ],
    commonIcd10: ["K05.6", "K05.5", "K05.3", "K05.4", "K06.9", "M26.69", "K08.5"],
    commonCpt: "CDT D4341-D4346, D4241-D4249, D4260-D4268, D4910",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive periodontics SOAP note following AAP 2018 Classification. Include: chief complaint, periodontal history with prior treatment, risk factor assessment (smoking, diabetes), full-mouth 6-point periodontal charting (probing depths, BOP, recession, CAL, furcation, mobility), radiographic bone level assessment, AAP 2018 diagnosis with staging (I-IV) and grading (A-C), and a phased treatment plan (SRP, surgery, maintenance).`,
  },

  "oral-surgery": {
    clinicType: "dental",
    label: "Oral Surgery",
    standard: "AAOMS Clinical Documentation — SOAP with surgical findings and post-operative care",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Surgical concern: tooth extraction, impacted tooth, biopsy, pathology, implant placement, orthognathic" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom history, prior treatment, reason for surgical intervention, urgency" },
      { id: "medicalHistory", label: "Medical History & Clearance", description: "ASA classification, anticoagulants, bisphosphonates, pregnancy, chemotherapy/radiation, cardiac/renal/hepatic disease, anesthesia risk assessment" },
      { id: "preopExam", label: "Pre-Operative Examination", description: "Extraoral/intraoral exam, cranial nerve assessment (V, VII), swelling, trismus, tooth numbering, pathology description" },
      { id: "imaging", label: "Radiographic Assessment", description: "Panoramic, CBCT, CT: pathology extent, tooth/nerve relationships (IAN canal, mental foramen), sinus involvement, bone quality" },
      { id: "procedure", label: "Procedure Details", description: "Anesthesia type (local, IV sedation, general), incision design, osteotomy, tooth sectioning, closure, specimen sent for pathology" },
      { id: "findings", label: "Intra-operative Findings", description: "Anatomical variations, pathology appearance, implant stability (ISQ), bone quality (Lekholm-Zarb), complications" },
      { id: "postOp", label: "Post-Operative Instructions", description: "Hemostasis, pain management (analgesics), antibiotics if indicated, diet, oral hygiene, activity restrictions, follow-up, emergency instructions" },
      { id: "pathology", label: "Pathology Results", description: "Gross description, histologic diagnosis, margins" },
      { id: "assessment", label: "Assessment & Plan", description: "ICD-10 codes, healing status, future treatment needs (implant restoration, prosthetic)" },
    ],
    assessmentScales: [
      { id: "asaClass", label: "ASA Physical Status", options: ["ASA I", "ASA II", "ASA III", "ASA IV"] },
      { id: "boneQuality", label: "Bone Quality (Lekholm-Zarb)", options: ["Type 1 - Homogeneous cortical", "Type 2 - Thick cortical with marrow", "Type 3 - Thin cortical with dense marrow", "Type 4 - Very thin cortical with low-density marrow"] },
    ],
    commonIcd10: ["K01.0", "K01.1", "K04.6", "K04.7", "K04.8", "M27.9", "S02.5", "K10.2", "K11.2"],
    commonCpt: "CDT D7111-D7251, D7210-D7240, D7950-D7953, D6010-D6040",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive oral surgery SOAP note following AAOMS documentation standards. Include: chief complaint, HPI, medical history with ASA classification and anesthesia risk, pre-op exam, imaging findings (CBCT/panoramic), detailed procedure description (anesthesia, incision, osteotomy, closure), intra-operative findings, post-operative instructions, pathology results when available, assessment with ICD-10 codes, and follow-up plan.`,
  },

  "prosthodontics": {
    clinicType: "dental",
    label: "Prosthodontics",
    standard: "ACP Clinical Documentation — SOAP with restorative and prosthetic assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Restorative concern: missing teeth, ill-fitting dentures, broken crown, esthetics, chewing difficulty" },
      { id: "hpi", label: "History of Present Illness", description: "Duration of edentulism, prior prosthetic history, reason for failure, patient expectations" },
      { id: "preprostheticExam", label: "Pre-Prosthetic Examination", description: "Edentulous ridge assessment, residual ridge classification, undercuts, tori, tissue health, saliva flow, occlusal plane, interarch space" },
      { id: "abutmentAssessment", label: "Abutment/Implant Assessment", description: "Tooth number, crown-to-root ratio, periodontal health, implant stability (ISQ), bone level, prosthetic space" },
      { id: "restorativePlan", label: "Restorative Treatment Plan", description: "Fixed (crown, bridge, implant crown/bridge, veneer, inlay/onlay) vs removable (complete denture, RPD, overdenture, implant-retained). Material selection: zirconia, PFM, lithium disilicate, composite" },
      { id: "impressions", label: "Impression / Digital Scan", description: "Impression technique, material, digital scan (STL), bite registration, shade selection" },
      { id: "prosthesisTryIn", label: "Prosthesis Try-In / Delivery", description: "Fit assessment, margin adaptation, proximal contacts, occlusion (centric, eccentric), esthetics (shade, contour), patient approval" },
      { id: "assessment", label: "Assessment & Plan", description: "ICD-10 codes, Kennedy classification for RPD, restorative status, maintenance schedule" },
    ],
    assessmentScales: [
      { id: "kennedyClass", label: "Kennedy Classification (RPD)", options: ["Class I - Bilateral edentulous posterior", "Class II - Unilateral edentulous posterior", "Class III - Unilateral edentulous with anterior/posterior abutment", "Class IV - Anterior edentulous crossing midline"] },
      { id: "crownRootRatio", label: "Crown-to-Root Ratio", description: "Ideal >1:2, acceptable 1:1, compromised <1:1" },
    ],
    commonIcd10: ["K08.1", "K08.4", "K08.5", "K08.9", "M26.37", "M26.22", "Z46.3", "Z96.5"],
    commonCpt: "CDT D2710-D2799, D5110-D5281, D6010-D6086, D6200-D6299",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive prosthodontics SOAP note following ACP documentation standards. Include: chief complaint, prosthetic history, pre-prosthetic exam (ridge assessment, occlusion, interarch space), abutment/implant assessment, restorative treatment plan with material selection and Kennedy classification, impression/digital scan details, prosthesis try-in findings (fit, occlusion, esthetics), assessment with ICD-10 codes, and maintenance plan.`,
  },

  "pediatric-dentistry": {
    clinicType: "dental",
    label: "Pediatric Dentistry",
    standard: "AAPD Clinical Practice Guidelines — SOAP with age-appropriate caries risk and growth assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Child's dental concern from parent/guardian" },
      { id: "hpi", label: "History of Present Illness", description: "Pain history, behavior concerns, trauma, dietary habits (bottle use, sippy cup, sugar frequency)" },
      { id: "medicalHistory", label: "Medical History", description: "Developmental milestones, chronic conditions, medications, allergies, anesthesia risk" },
      { id: "dentalHistory", label: "Dental History", description: "Fluoride exposure (water, supplements, varnish), prior dental visits, sealants, caries history, oral hygiene habits" },
      { id: "growthAssessment", label: "Growth & Development", description: "Dental age vs chronological age, eruption status (primary/mixed/permanent dentition), Nolla staging for developing teeth, space analysis" },
      { id: "oralExam", label: "Intraoral Examination", description: "Tooth numbering (primary A-T, permanent 1-32), caries charting, soft tissue, eruption sequence, crowding, occlusal development" },
      { id: "cariesRisk", label: "Caries Risk Assessment", description: "AAPD Caries Risk Assessment Tool (C.R.A.T.): biological factors, protective factors, clinical findings" },
      { id: "behavior", label: "Behavior Assessment", description: "Frankl behavior rating scale, cooperation level, need for behavior guidance (tell-show-do, protective stabilization, sedation, GA)" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 codes, AAPD caries risk level, treatment needs" },
      { id: "plan", label: "Treatment Plan", description: "Preventive (fluoride varnish, sealants, OHI), restorative (composite, SSCs, pulpotomy/pulpectomy, extraction), behavior guidance approach, recall interval" },
    ],
    assessmentScales: [
      { id: "cariesRiskPediatric", label: "AAPD Caries Risk", options: ["Low", "Moderate", "High"] },
      { id: "franklBehavior", label: "Frankl Behavior Rating", options: ["1 - Definitely negative", "2 - Negative", "3 - Positive", "4 - Definitely positive"] },
    ],
    commonIcd10: ["K02.9", "K04.7", "K00.6", "K01.1", "M26.10", "S02.5", "Z01.21", "K02.51", "K02.61"],
    commonCpt: "CDT D1120-D1354, D2120-D2394, D2930-D2940, D3220-D3240",
    billingCodeSet: "cdt",
    aiPrompt: `Generate a comprehensive pediatric dentistry SOAP note following AAPD guidelines. Include: chief complaint from parent, HPI with dietary and habit history, medical history and developmental assessment, growth and eruption status, intraoral exam with primary/permanent tooth numbering, AAPD Caries Risk Assessment (C.R.A.T.), Frankl behavior rating, radiographic findings, assessment with ICD-10 codes and caries risk level, and treatment plan including preventive, restorative, and behavior guidance approach.`,
  },

  "small-animal": {
    clinicType: "veterinary",
    label: "Small Animal (Dogs & Cats)",
    standard: "AAHA/AVMA Medical Record Standards — SOAP with species-specific examination",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Reason for visit from owner (lameness, vomiting, lethargy, routine wellness, vaccination)" },
      { id: "signalment", label: "Signalment", description: "Species, breed, age, sex (intact/neutered/spayed), weight, body condition score (1-9)" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom onset, duration, progression, appetite, thirst, urination, defecation, activity level, vaccination status, travel history" },
      { id: "tpr", label: "Physical Examination (TPR)", description: "Temperature, pulse (rate, rhythm, quality), respiration (rate, effort), mucous membranes, CRT, hydration status" },
      { id: "physicalExam", label: "Systems Examination", description: "HEENT, cardiovascular (auscultation, pulses), respiratory, abdominal palpation, musculoskeletal, neurological, skin/coat, lymph nodes, rectal/genitourinary" },
      { id: "diagnostics", label: "Diagnostic Tests", description: "CBC, chemistry panel, urinalysis, heartworm test, FeLV/FIV (feline), 4DX (canine), radiographs, ultrasound, cytology" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 codes or SNOMED-CT/Veterinary terms, problem list, differential diagnoses" },
      { id: "plan", label: "Plan", description: "Treatment (medications, dosage, route, frequency), preventive care (vaccines, parasite control, dental), nutrition, follow-up, owner education" },
    ],
    assessmentScales: [
      { id: "bcs", label: "Body Condition Score", options: ["1-3 Underweight", "4-5 Ideal", "6-9 Overweight/Obese"] },
      { id: "painScale", label: "Veterinary Pain Scale", options: ["0 - No pain", "1-3 Mild", "4-6 Moderate", "7-9 Severe", "10 - Worst possible"] },
    ],
    commonIcd10: ["C00-Z99 (adapted)", "K30", "J06.9", "M25.50", "L08.9", "K52.9", "N39.0"],
    commonCpt: "Species/condition-specific coding",
    billingCodeSet: "mixed",
    aiPrompt: `Generate a comprehensive small animal veterinary SOAP note following AAHA/AVMA standards. Include: chief complaint from owner, complete signalment (species, breed, age, sex, weight, BCS 1-9), detailed HPI with appetite/ thirst/ urination/ defecation, full TPR and physical exam by systems, diagnostic test results and interpretation, problem list with differential diagnoses, and a detailed treatment plan with drug dosages and preventive care recommendations.`,
  },

  "equine": {
    clinicType: "veterinary",
    label: "Equine (Horses)",
    standard: "AAEP Clinical Documentation Guidelines — SOAP with lameness and performance assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Equine concern: lameness, colic, respiratory issue, vaccination, dental, pre-purchase exam" },
      { id: "signalment", label: "Signalment & History", description: "Breed, age, sex, color, markings, use (pleasure, show, race, breeding), vaccination/deworming status, Coggins test, farrier schedule" },
      { id: "hpi", label: "History of Present Illness", description: "Lameness: onset, duration, severity, affected limb(s), performance decline, previous treatments, response to rest/medication" },
      { id: "tpr", label: "Vital Signs (TPR)", description: "Temperature (37.2-38.3°C), pulse (28-44 bpm adult), respiration (10-24 bpm), gut sounds, mucous membranes, CRT, hydration" },
      { id: "lamenessExam", label: "Lameness Examination", description: "AAEP lameness grading scale (0-5), flexion tests, hoof testers, lunging (soft/hard surface, circle direction), nerve blocks (perineural, intrasynovial), response to flexion" },
      { id: "imaging", label: "Diagnostic Imaging", description: "Radiographic views and findings, ultrasound (tendons, ligaments), nuclear scintigraphy, MRI, CT" },
      { id: "dental", label: "Dental Assessment", description: "Dental float findings, wolf teeth, hooks/ramps, wave mouth, periodontal pockets, tooth numbering (Triadan system)" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "Problem list, AAEP lameness grade, anatomical diagnosis, etiological diagnosis" },
      { id: "plan", label: "Plan", description: "Treatment: joint therapy, hoof care, medication (doses for equine), rest/rehab protocol, vaccine schedule, deworming, follow-up imaging" },
    ],
    assessmentScales: [
      { id: "aaepLameness", label: "AAEP Lameness Grade", options: ["0 - No lameness", "1 - Difficult to observe", "2 - Consistent under saddle", "3 - Observable at trot", "4 - Obvious lameness, head nod", "5 - Minimal weight bearing"] },
      { id: "bcsEquine", label: "Henneke Body Condition Score", options: ["1 - Poor", "2-3 - Moderate", "4-6 - Ideal", "7-8 - Overweight", "9 - Obese"] },
    ],
    commonIcd10: ["C00-Z99 (adapted)", "K59.0", "J06.9", "M25.50", "M60.9", "R09.8", "Z23"],
    commonCpt: "Equine-specific coding",
    billingCodeSet: "mixed",
    aiPrompt: `Generate a comprehensive equine veterinary SOAP note following AAEP guidelines. Include: chief complaint, complete signalment with use/discipline, detailed HPI, TPR and vital signs, AAEP lameness exam (grade 0-5, flexion, nerve blocks, lunging), diagnostic imaging findings, dental assessment (Triadan system, float findings), assessment with AAEP lameness grade, and a detailed treatment plan with equine-specific drug dosages and rehab protocol.`,
  },

  "exotic-pets": {
    clinicType: "veterinary",
    label: "Exotic Pets (Avian, Reptile, Small Mammal)",
    standard: "ABVP/AVMA Species-Specific Guidelines — SOAP with environmental and nutritional assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Species-specific concern from owner: lethargy, anorexia, respiratory distress, feather picking, shell issues, diarrhea" },
      { id: "signalment", label: "Signalment", description: "Species, common name, age, sex, weight, color/morph, source (breeder, pet store, rescue)" },
      { id: "husbandry", label: "Husbandry & Environment", description: "Enclosure type/size, substrate, temperature gradient, humidity, UVB lighting (reptiles), photoperiod, cage mates, outdoor access" },
      { id: "diet", label: "Diet & Nutrition", description: "Diet composition, supplements (calcium, vitamins), feeding schedule, appetite changes, water source" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom onset, duration, progression, previous treatment, quarantine history" },
      { id: "physicalExam", label: "Physical Examination", description: "General condition, BCS, hydration, skin/feathers/scale condition, eyes/ears/nose, oral cavity (beak, glottis), coelomic palpation, auscultation, vent examination" },
      { id: "diagnostics", label: "Diagnostic Tests", description: "Species-specific: CBC, chemistries (avian/reptile panels), fecal exam (direct, float, Gram stain), radiographs, endoscopy, PCR testing" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "Problem list, differential diagnoses, species-specific conditions" },
      { id: "plan", label: "Plan", description: "Species-appropriate treatment (drug dosages per species), environmental corrections, diet modification, supportive care, follow-up" },
    ],
    assessmentScales: [
      { id: "bcsExotic", label: "Body Condition Score (Species-Specific)", options: ["1 - Emaciated", "2 - Underweight", "3 - Ideal", "4 - Overweight", "5 - Obese"] },
    ],
    commonIcd10: ["A00-B99, C00-Z99 (adapted)", "K52.9", "J06.9", "M25.50", "L08.9", "B07.9", "A09"],
    commonCpt: "Species-specific coding",
    billingCodeSet: "mixed",
    aiPrompt: `Generate a comprehensive exotic pet SOAP note following ABVP species-specific guidelines. Include: chief complaint, complete signalment (species, age, sex, weight), detailed husbandry/environmental assessment (enclosure, temperature, humidity, UVB, photoperiod), diet evaluation, HPI, species-appropriate physical exam findings, diagnostic test results, problem list with differentials, and a detailed treatment plan with species-specific drug dosages, environmental corrections, and nutritional recommendations.`,
  },

  "large-animal": {
    clinicType: "veterinary",
    label: "Large Animal (Bovine, Ovine, Caprine)",
    standard: "AABP/AVMA Clinical Documentation — SOAP with herd health and production assessment",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Individual or herd concern: lameness, mastitis, respiratory disease, reproductive issue, digestive problem, down cow" },
      { id: "signalment", label: "Signalment & Identification", description: "Species, breed, age, sex, ID (ear tag, tattoo, brand), lactation stage, pregnancy stage, BCS" },
      { id: "herdHistory", label: "Herd History & Management", description: "Herd size, production system (dairy, beef, feedlot, organic), vaccination program, biosecurity, nutrition, housing, mortality/morbidity" },
      { id: "hpi", label: "History of Present Illness", description: "Individual: onset, duration, appetite, milk production, fecal output, urination, gait. Herd: attack rate, affected groups, new introductions" },
      { id: "tpr", label: "Clinical Examination", description: "Temperature, heart rate, respiration, rumen motility, hydration, mucous membranes, fecal character" },
      { id: "systemsExam", label: "Systems Examination", description: "Respiratory (lung auscultation, nasal discharge), digestive (rumen, cud chewing, manure), reproductive (pregnancy check, uterine discharge), udder (mastitis, CMT), musculoskeletal/hoof (lameness, foot rot)" },
      { id: "diagnostics", label: "Diagnostic Tests", description: "Milk culture/CBT, blood work (BHB, calcium, PCV/total protein), fecal float, Johne's ELISA, brucellosis/TB tests, BVD PCR, radiographs/ultrasound" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 adapted codes, individual diagnosis, herd-level problem diagnosis" },
      { id: "plan", label: "Treatment & Management Plan", description: "Individual: drug therapy (doses, withdrawal times), supportive care, nursing. Herd: vaccination changes, biosecurity, nutrition adjustment, culling decisions. Withdrawal times for meat/milk" },
    ],
    assessmentScales: [
      { id: "bcsLargeAnimal", label: "BCS (1-9 or 1-5 scale)", description: "Species-specific: 1=emaciated, 5=ideal (for 1-5 scale), 9=obese (for 1-9 scale)" },
      { id: "lamenessCow", label: "Bovine Lameness Score", options: ["0 - Normal", "1 - Mildly lame", "2 - Moderately lame", "3 - Lame, weight-shifting", "4 - Severely lame, non-weight-bearing"] },
    ],
    commonIcd10: ["C00-Z99 (adapted)", "J06.9", "M25.50", "K52.9", "N61", "N39.0", "Z23", "A09"],
    commonCpt: "Large animal-specific coding",
    billingCodeSet: "mixed",
    aiPrompt: `Generate a comprehensive large animal veterinary SOAP note following AABP guidelines. Include: chief complaint (individual or herd level), signalment with ID and lactation/pregnancy stage, herd history (production system, vaccination, nutrition), detailed HPI, complete clinical exam (TPR, rumen, systems), diagnostic test results, individual and herd-level assessment, and a treatment plan WITH DRUG WITHDRAWAL TIMES for meat and milk.`,
  },

  "mixed-animal": {
    clinicType: "veterinary",
    label: "Mixed Animal Practice",
    standard: "AVMA Mixed Practice Documentation — SOAP with species-appropriate sections based on patient type",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Reason for visit (species-specific concern)" },
      { id: "signalment", label: "Signalment & Patient ID", description: "Species, breed, age, sex, weight, identifying features, use/purpose" },
      { id: "hpi", label: "History of Present Illness", description: "Symptom onset, duration, previous treatment, vaccination/deworming history" },
      { id: "exam", label: "Physical Examination", description: "Species-appropriate TPR and systems exam" },
      { id: "diagnostics", label: "Diagnostic Tests", description: "Species-appropriate laboratory and imaging" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 adapted codes, problem list" },
      { id: "plan", label: "Plan", description: "Treatment with species-appropriate drug dosages and withdrawal times, prevention" },
    ],
    assessmentScales: [],
    commonIcd10: ["A00-Z99 (adapted)", "Z00.8", "Z23", "Z71.8"],
    commonCpt: "Species-specific coding by patient type",
    billingCodeSet: "mixed",
    aiPrompt: `Generate a comprehensive veterinary SOAP note appropriate for the patient's species. Adapt the examination and treatment sections based on whether the patient is small animal, equine, large animal, or exotic. Include species-appropriate signalment, examination findings, diagnostic tests, and treatment plans with proper drug dosages and withdrawal times.`,
  },

  "vet-specialty": {
    clinicType: "veterinary",
    label: "Veterinary Specialty (Surgery/Ophthalmology)",
    standard: "ACVS/ACVO Specialty Guidelines — SOAP with surgical or ophthalmic specialty focus",
    sections: [
      { id: "chiefComplaint", label: "Chief Complaint", description: "Specialty referral concern: surgical condition, ophthalmic issue, complex medical case" },
      { id: "signalment", label: "Signalment", description: "Species, breed, age, sex, weight, BCS" },
      { id: "referralHistory", label: "Referring History", description: "Referring veterinarian, prior diagnostics and treatments, reason for referral" },
      { id: "specialtyExam", label: "Specialty Examination", description: "Surgery: orthopedic (lameness, drawer sign, Ortolani), neurologic (spinal reflexes, CN exam), soft tissue (mass palpation, wound assessment). Ophthalmology: STT, IOP, fluorescein, slit lamp, fundoscopy, Schirmer tear test" },
      { id: "diagnostics", label: "Diagnostic Tests", description: "Advanced imaging (MRI, CT, arthroscopy), biopsy, cytology, histopathology, genetic testing" },
      { id: "surgicalPlan", label: "Surgical/Medical Plan", description: "Procedure details, anesthesia plan, analgesia, post-op monitoring, medications" },
      { id: "assessment", label: "Assessment & Diagnosis", description: "ICD-10 adapted codes, specialty diagnosis, prognosis" },
      { id: "plan", label: "Plan", description: "Pre-op preparation, surgical/medical treatment, post-op care, recheck schedule, owner communication" },
    ],
    assessmentScales: [
      { id: "veterinaryPainScale", label: "Veterinary Pain Scale", options: ["0 - No pain", "1-3 Mild", "4-6 Moderate", "7-9 Severe", "10 - Worst possible"] },
    ],
    commonIcd10: ["C00-Z99 (adapted)", "M25.50", "H05.9", "H00.0", "H01.0", "H10.9", "H16.9", "H25.9", "H40.9"],
    commonCpt: "Specialty-specific coding",
    billingCodeSet: "mixed",
    aiPrompt: `Generate a comprehensive veterinary specialty SOAP note following ACVS/ACVO standards. Include: chief complaint, signalment, referring veterinarian history, specialty examination findings (orthopedic/neurologic for surgery, ophthalmic exam for ophthalmology), advanced diagnostic test results, surgical or medical plan with anesthesia and analgesia details, assessment with specialty diagnosis and prognosis, and detailed post-operative care and recheck plan.`,
  },
};

export function getReportTemplate(specialty) {
  return REPORT_TEMPLATES[specialty] || REPORT_TEMPLATES["general-practice"];
}

export function getTemplatesForClinicType(clinicType) {
  return Object.entries(REPORT_TEMPLATES)
    .filter(([, t]) => t.clinicType === clinicType)
    .map(([id, t]) => ({ id, label: t.label, standard: t.standard, sections: t.sections }));
}
