import mongoose from "mongoose";
import Icd10Code from "../models/Icd10Code.js";

const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/oriveo";

const ICD10_CODES = [
  // General / Primary Care
  { code: "A00.0", name: "Cholera due to Vibrio cholerae", category: "infectious", specialty: ["general"] },
  { code: "A09", name: "Infectious gastroenteritis and colitis, unspecified", category: "gastrointestinal", specialty: ["general"] },
  { code: "A49.9", name: "Bacterial infection, unspecified", category: "infectious", specialty: ["general"] },
  { code: "B34.9", name: "Viral infection, unspecified", category: "infectious", specialty: ["general"] },
  { code: "B99", name: "Other and unspecified infectious diseases", category: "infectious", specialty: ["general"] },
  { code: "D50.9", name: "Iron deficiency anemia, unspecified", category: "hematology", specialty: ["general"] },
  { code: "D64.9", name: "Anemia, unspecified", category: "hematology", specialty: ["general"] },
  { code: "E03.9", name: "Hypothyroidism, unspecified", category: "endocrine", specialty: ["general", "endocrinology"] },
  { code: "E04.9", name: "Nontoxic goiter, unspecified", category: "endocrine", specialty: ["general", "endocrinology"] },
  { code: "E10.9", name: "Type 1 diabetes mellitus without complications", category: "endocrine", specialty: ["endocrinology"] },
  { code: "E11.9", name: "Type 2 diabetes mellitus without complications", category: "endocrine", specialty: ["general", "endocrinology"] },
  { code: "E55.9", name: "Vitamin D deficiency, unspecified", category: "nutritional", specialty: ["general"] },
  { code: "E66.9", name: "Obesity, unspecified", category: "metabolic", specialty: ["general", "endocrinology"] },
  { code: "E78.5", name: "Hyperlipidemia, unspecified", category: "metabolic", specialty: ["general"] },
  { code: "E86.0", name: "Dehydration", category: "metabolic", specialty: ["general"] },
  { code: "F32.9", name: "Major depressive disorder, single episode, unspecified", category: "mental", specialty: ["general"] },
  { code: "F41.1", name: "Generalized anxiety disorder", category: "mental", specialty: ["general"] },
  { code: "F41.9", name: "Anxiety disorder, unspecified", category: "mental", specialty: ["general"] },
  { code: "G43.909", name: "Migraine, unspecified, not intractable, without status migrainosus", category: "neurology", specialty: ["general"] },
  { code: "G47.00", name: "Insomnia, unspecified", category: "neurology", specialty: ["general"] },
  { code: "G47.33", name: "Obstructive sleep apnea (adult) (pediatric)", category: "respiratory", specialty: ["general"] },
  { code: "G89.29", name: "Other chronic pain", category: "neurology", specialty: ["general"] },
  { code: "H25.9", name: "Unspecified age-related cataract", category: "ophthalmology", specialty: ["general"] },
  { code: "H61.23", name: "Impacted cerumen, bilateral", category: "ent", specialty: ["general"] },
  { code: "H66.9", name: "Otitis media, unspecified", category: "ent", specialty: ["general"] },
  { code: "H81.9", name: "Unspecified disorder of vestibular function", category: "ent", specialty: ["general"] },
  { code: "I10", name: "Essential (primary) hypertension", category: "cardiovascular", specialty: ["general", "cardiology"] },
  { code: "I25.10", name: "Atherosclerotic heart disease of native coronary artery without angina pectoris", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I25.110", name: "Atherosclerotic heart disease of native coronary artery with unstable angina pectoris", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I42.0", name: "Dilated cardiomyopathy", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I47.2", name: "Ventricular tachycardia", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I48.0", name: "Paroxysmal atrial fibrillation", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I48.2", name: "Chronic atrial fibrillation", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I48.91", name: "Unspecified atrial fibrillation", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I49.9", name: "Cardiac arrhythmia, unspecified", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "I50.9", name: "Heart failure, unspecified", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "J00", name: "Acute nasopharyngitis [common cold]", category: "respiratory", specialty: ["general"] },
  { code: "J01.9", name: "Acute sinusitis, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J02.9", name: "Acute pharyngitis, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J03.9", name: "Acute tonsillitis, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J06.9", name: "Acute upper respiratory infection, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J15.9", name: "Unspecified bacterial pneumonia", category: "respiratory", specialty: ["general"] },
  { code: "J20.9", name: "Acute bronchitis, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J30.9", name: "Allergic rhinitis, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J32.9", name: "Chronic sinusitis, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J44.9", name: "Chronic obstructive pulmonary disease, unspecified", category: "respiratory", specialty: ["general"] },
  { code: "J45.20", name: "Mild intermittent asthma, uncomplicated", category: "respiratory", specialty: ["general"] },
  { code: "J45.21", name: "Mild persistent asthma with (acute) exacerbation", category: "respiratory", specialty: ["general"] },
  { code: "K02.9", name: "Dental caries, unspecified", category: "dental", specialty: ["dentistry"] },
  { code: "K03.81", name: "Cracked tooth", category: "dental", specialty: ["dentistry"] },
  { code: "K04.0", name: "Pulpitis", category: "dental", specialty: ["dentistry"] },
  { code: "K04.7", name: "Periapical abscess without sinus", category: "dental", specialty: ["dentistry"] },
  { code: "K05.00", name: "Acute gingivitis, plaque induced", category: "dental", specialty: ["dentistry"] },
  { code: "K05.10", name: "Chronic gingivitis, plaque induced", category: "dental", specialty: ["dentistry"] },
  { code: "K05.20", name: "Aggressive periodontitis, generalized", category: "dental", specialty: ["dentistry"] },
  { code: "K05.30", name: "Chronic periodontitis, generalized", category: "dental", specialty: ["dentistry"] },
  { code: "K08.101", name: "Complete edentulism, class I", category: "dental", specialty: ["dentistry"] },
  { code: "K08.402", name: "Partially edentulous, class II", category: "dental", specialty: ["dentistry"] },
  { code: "K09.0", name: "Developmental odontogenic cysts", category: "dental", specialty: ["dentistry"] },
  { code: "K12.0", name: "Recurrent oral aphthae", category: "dental", specialty: ["dentistry"] },
  { code: "K21.9", name: "Gastro-esophageal reflux disease without esophagitis", category: "gastrointestinal", specialty: ["general"] },
  { code: "K29.50", name: "Chronic gastritis, unspecified, without bleeding", category: "gastrointestinal", specialty: ["general"] },
  { code: "K30", name: "Functional dyspepsia", category: "gastrointestinal", specialty: ["general"] },
  { code: "K35.80", name: "Unspecified appendicitis", category: "gastrointestinal", specialty: ["general"] },
  { code: "K42.9", name: "Umbilical hernia without obstruction or gangrene", category: "gastrointestinal", specialty: ["general"] },
  { code: "K44.9", name: "Diaphragmatic hernia without obstruction or gangrene", category: "gastrointestinal", specialty: ["general"] },
  { code: "K59.00", name: "Constipation, unspecified", category: "gastrointestinal", specialty: ["general"] },
  { code: "K70.9", name: "Alcoholic liver disease, unspecified", category: "hepatic", specialty: ["general"] },
  { code: "L02.91", name: "Cutaneous abscess, unspecified site", category: "dermatology", specialty: ["general"] },
  { code: "L03.90", name: "Cellulitis, unspecified", category: "dermatology", specialty: ["general"] },
  { code: "L20.9", name: "Atopic dermatitis, unspecified", category: "dermatology", specialty: ["general"] },
  { code: "L30.9", name: "Dermatitis, unspecified", category: "dermatology", specialty: ["general"] },
  { code: "L40.0", name: "Psoriasis vulgaris", category: "dermatology", specialty: ["general"] },
  { code: "L60.0", name: "Ingrowing nail", category: "dermatology", specialty: ["general"] },
  { code: "M06.9", name: "Rheumatoid arthritis, unspecified", category: "rheumatology", specialty: ["general"] },
  { code: "M17.9", name: "Osteoarthritis of knee, unspecified", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M19.90", name: "Unspecified osteoarthritis, unspecified site", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M23.50", name: "Chronic instability of knee, unspecified", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M24.10", name: "Other articular cartilage disorders, unspecified joint", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M25.50", name: "Pain in unspecified joint", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M25.561", name: "Pain in right knee", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M51.06", name: "Lumbar disc degeneration", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M51.16", name: "Lumbar disc displacement", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M54.2", name: "Cervicalgia", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M54.3", name: "Sciatica", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M54.4", name: "Lumbago with sciatica", category: "orthopedic", specialty: ["orthopedics"] },
  { code: "M54.5", name: "Low back pain", category: "orthopedic", specialty: ["general", "orthopedics"] },
  { code: "N39.0", name: "Urinary tract infection, site not specified", category: "urology", specialty: ["general"] },
  { code: "N40.0", name: "Benign prostatic hyperplasia without lower urinary tract symptoms", category: "urology", specialty: ["general"] },
  { code: "R00.0", name: "Tachycardia, unspecified", category: "general", specialty: ["general", "cardiology"] },
  { code: "R05", name: "Cough", category: "respiratory", specialty: ["general"] },
  { code: "R05.1", name: "Acute cough", category: "respiratory", specialty: ["general"] },
  { code: "R05.2", name: "Subacute cough", category: "respiratory", specialty: ["general"] },
  { code: "R05.3", name: "Chronic cough", category: "respiratory", specialty: ["general"] },
  { code: "R06.02", name: "Shortness of breath", category: "respiratory", specialty: ["general", "cardiology"] },
  { code: "R10.0", name: "Acute abdomen", category: "gastrointestinal", specialty: ["general"] },
  { code: "R10.9", name: "Unspecified abdominal pain", category: "gastrointestinal", specialty: ["general"] },
  { code: "R11.0", name: "Nausea", category: "gastrointestinal", specialty: ["general"] },
  { code: "R11.10", name: "Vomiting, unspecified", category: "gastrointestinal", specialty: ["general"] },
  { code: "R30.0", name: "Dysuria", category: "urology", specialty: ["general"] },
  { code: "R31.0", name: "Gross hematuria", category: "urology", specialty: ["general"] },
  { code: "R31.9", name: "Hematuria, unspecified", category: "urology", specialty: ["general"] },
  { code: "R32", name: "Unspecified urinary incontinence", category: "urology", specialty: ["general"] },
  { code: "R41.82", name: "Altered mental status, unspecified", category: "neurology", specialty: ["general"] },
  { code: "R42", name: "Dizziness and giddiness", category: "neurology", specialty: ["general"] },
  { code: "R50.9", name: "Fever, unspecified", category: "general", specialty: ["general"] },
  { code: "R51", name: "Headache", category: "neurology", specialty: ["general"] },
  { code: "R51.0", name: "Headache with orthostatic component", category: "neurology", specialty: ["general"] },
  { code: "R51.9", name: "Headache, unspecified", category: "neurology", specialty: ["general"] },
  { code: "R52", name: "Pain, unspecified", category: "general", specialty: ["general"] },
  { code: "R53.1", name: "Weakness", category: "general", specialty: ["general"] },
  { code: "R53.81", name: "Other malaise", category: "general", specialty: ["general"] },
  { code: "R53.83", name: "Other fatigue", category: "general", specialty: ["general"] },
  { code: "R55", name: "Syncope and collapse", category: "cardiovascular", specialty: ["general", "cardiology"] },
  { code: "R56.9", name: "Unspecified convulsions", category: "neurology", specialty: ["general"] },
  { code: "R60.0", name: "Localized edema", category: "cardiovascular", specialty: ["general"] },
  { code: "R73.01", name: "Impaired fasting glucose", category: "endocrine", specialty: ["general", "endocrinology"] },
  { code: "R73.02", name: "Impaired glucose tolerance (oral)", category: "endocrine", specialty: ["general", "endocrinology"] },
  { code: "R73.03", name: "Prediabetes", category: "endocrine", specialty: ["general", "endocrinology"] },
  { code: "R79.89", name: "Other specified abnormal findings of blood chemistry", category: "general", specialty: ["general"] },
  { code: "R80.9", name: "Proteinuria, unspecified", category: "urology", specialty: ["general"] },
  { code: "R91.1", name: "Solitary pulmonary nodule", category: "respiratory", specialty: ["general"] },
  { code: "R94.31", name: "Abnormal electrocardiogram [ECG] [EKG]", category: "cardiovascular", specialty: ["cardiology"] },
  { code: "S00.01XA", name: "Abrasion of scalp, initial encounter", category: "trauma", specialty: ["general"] },
  { code: "S06.9X9A", name: "Unspecified intracranial injury, initial encounter", category: "trauma", specialty: ["general"] },
  { code: "S09.90XA", name: "Unspecified injury of head, initial encounter", category: "trauma", specialty: ["general"] },
  { code: "S22.009A", name: "Fracture of unspecified thoracic vertebra, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "S32.001A", name: "Fracture of lumbar vertebra, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "S52.509A", name: "Unspecified fracture of lower end of radius, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "S62.609A", name: "Fracture of unspecified phalanx of hand, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "S72.009A", name: "Fracture of head of femur, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "S82.001A", name: "Fracture of patella, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "S93.409A", name: "Sprain of unspecified ankle, initial encounter", category: "trauma", specialty: ["orthopedics"] },
  { code: "T14.90XA", name: "Injury, unspecified, initial encounter", category: "trauma", specialty: ["general"] },
  { code: "T78.40XA", name: "Allergy, unspecified, initial encounter", category: "general", specialty: ["general"] },
  { code: "Z00.00", name: "Encounter for general adult medical examination without abnormal findings", category: "preventive", specialty: ["general"] },
  { code: "Z00.01", name: "Encounter for general adult medical examination with abnormal findings", category: "preventive", specialty: ["general"] },
  { code: "Z00.129", name: "Encounter for routine child health examination without abnormal findings", category: "preventive", specialty: ["general"] },
  { code: "Z01.30", name: "Encounter for examination of blood pressure without abnormal findings", category: "preventive", specialty: ["general"] },
  { code: "Z01.411", name: "Encounter for hearing examination following failed hearing screening", category: "preventive", specialty: ["general"] },
  { code: "Z01.818", name: "Encounter for other preprocedural examination", category: "preventive", specialty: ["general"] },
  { code: "Z11.2", name: "Encounter for screening for malnutrition", category: "preventive", specialty: ["general"] },
  { code: "Z12.10", name: "Encounter for screening for malignant neoplasm of intestinal tract", category: "preventive", specialty: ["general"] },
  { code: "Z12.31", name: "Encounter for screening mammogram for breast cancer", category: "preventive", specialty: ["general"] },
  { code: "Z13.0", name: "Encounter for screening for diabetes mellitus", category: "preventive", specialty: ["general", "endocrinology"] },
  { code: "Z13.220", name: "Encounter for screening for lipid disorders", category: "preventive", specialty: ["general"] },
  { code: "Z20.828", name: "Contact with and (suspected) exposure to COVID-19", category: "infectious", specialty: ["general"] },
  { code: "Z22.2", name: "Carrier of typhoid", category: "infectious", specialty: ["general"] },
  { code: "Z23", name: "Encounter for immunization", category: "preventive", specialty: ["general"] },
  { code: "Z28.9", name: "Immunization not carried out for other reason", category: "preventive", specialty: ["general"] },
  { code: "Z30.011", name: "Encounter for initial prescription of oral contraceptives", category: "reproductive", specialty: ["general"] },
  { code: "Z33.1", name: "Pregnant state, incidental", category: "reproductive", specialty: ["general"] },
  { code: "Z34.90", name: "Encounter for supervision of normal pregnancy, unspecified trimester", category: "reproductive", specialty: ["general"] },
  { code: "Z71.1", name: "Person with feared health complaint in whom no diagnosis is made", category: "mental", specialty: ["general"] },
  { code: "Z71.3", name: "Dietary counseling and surveillance", category: "preventive", specialty: ["general"] },
  { code: "Z71.7", name: "Human immunodeficiency virus [HIV] counseling", category: "preventive", specialty: ["general"] },
  { code: "Z72.0", name: "Tobacco use", category: "preventive", specialty: ["general"] },
  { code: "Z76.89", name: "Persons encountering health services in other specified circumstances", category: "general", specialty: ["general"] },
  { code: "Z79.01", name: "Long term (current) use of anticoagulants", category: "medication", specialty: ["general", "cardiology"] },
  { code: "Z79.4", name: "Long term (current) use of insulin", category: "medication", specialty: ["endocrinology"] },
  { code: "Z79.82", name: "Long term (current) use of aspirin", category: "medication", specialty: ["general", "cardiology"] },
  { code: "Z79.891", name: "Long term (current) use of opiate analgesic", category: "medication", specialty: ["general"] },
  { code: "Z79.899", name: "Other long term (current) drug therapy", category: "medication", specialty: ["general"] },
  { code: "Z81.0", name: "Family history of intellectual disabilities", category: "family_history", specialty: ["general"] },
  { code: "Z82.49", name: "Family history of ischemic heart disease", category: "family_history", specialty: ["general", "cardiology"] },
  { code: "Z83.3", name: "Family history of diabetes mellitus", category: "family_history", specialty: ["general", "endocrinology"] },
  { code: "Z86.73", name: "Personal history of transient ischemic attack (TIA), and cerebral infarction", category: "history", specialty: ["general", "cardiology"] },
  { code: "Z87.898", name: "Personal history of other specified conditions", category: "history", specialty: ["general"] },
  { code: "Z88.0", name: "Allergy status to penicillin", category: "allergy", specialty: ["general"] },
  { code: "Z88.1", name: "Allergy status to other antibiotic agents", category: "allergy", specialty: ["general"] },
  { code: "Z88.8", name: "Allergy status to other drugs, medicaments and biological substances", category: "allergy", specialty: ["general"] },
  { code: "Z90.01", name: "Acquired absence of breast", category: "surgical_history", specialty: ["general"] },
  { code: "Z92.82", name: "Status post administration of tPA (rtPA) in a different facility", category: "history", specialty: ["general", "cardiology"] },
  { code: "Z95.1", name: "Presence of aortocoronary bypass graft", category: "cardiac_history", specialty: ["cardiology"] },
  { code: "Z95.5", name: "Presence of coronary angioplasty implant and graft", category: "cardiac_history", specialty: ["cardiology"] },
  { code: "Z96.1", name: "Presence of intraocular lens", category: "surgical_history", specialty: ["general"] },
];

async function seed() {
  const uri = process.argv[2] || MONGO_URI;
  await mongoose.connect(uri);
  console.log(`Connected to MongoDB: ${uri}`);

  const existing = await Icd10Code.countDocuments();
  if (existing > 0) {
    console.log(`Already have ${existing} ICD-10 codes. Dropping and reseeding...`);
    await Icd10Code.deleteMany({});
  }

  const docs = ICD10_CODES.map((c) => ({
    code: c.code.toUpperCase(),
    name: c.name,
    category: c.category || "",
    specialty: c.specialty || [],
  }));

  const result = await Icd10Code.insertMany(docs);
  console.log(`Seeded ${result.length} ICD-10 codes`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
