import Appointment from "../models/Appointment.js";
import Call from "../models/Call.js";
import Patient from "../models/Patient.js";
import User from "../models/User.js";
import Organization from "../models/Organization.js";
import { sendEmail } from "../services/emailService.js";
import { logger } from "./logger.js";

let intervalHandle = null;

export async function generateMonthlyReports() {
  try {
    const now = new Date();
    const firstOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const firstOfNextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1);

    const organizations = await Organization.find({ isActive: true });

    for (const org of organizations) {
      const match = { organization: org._id };

      const calls = await Call.find({
        ...match,
        createdAt: { $gte: firstOfMonth, $lt: firstOfNextMonth },
      });

      const appointments = await Appointment.find({
        ...match,
        date: { $gte: firstOfMonth, $lt: firstOfNextMonth },
      });

      const patientCount = await Patient.countDocuments(match);
      const userCount = await User.countDocuments({ ...match, isActive: true });

      const completedCalls = calls.filter((c) => c.status === "completed").length;
      const failedCalls = calls.filter((c) => c.status === "failed").length;
      const emergencyCalls = calls.filter((c) => c.emergencyDetected).length;
      const inboundCalls = calls.filter((c) => c.direction === "inbound").length;
      const outboundCalls = calls.filter((c) => c.direction !== "inbound").length;

      const totalAppointments = appointments.length;
      const noShows = appointments.filter((a) => a.status === "no-show").length;
      const cancellations = appointments.filter((a) => a.status === "cancelled").length;
      const completedAppts = appointments.filter((a) => a.status === "completed").length;

      const avgSeverity = calls.length > 0
        ? (calls.reduce((s, c) => s + (c.aiSeverityScore || 0), 0) / calls.length).toFixed(1)
        : "N/A";

      const owners = await User.find({ organization: org._id, role: "admin" }).limit(1);
      if (owners.length === 0) continue;
      const owner = owners[0];

      const html = `
<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #1f2937;">
  <div style="max-width: 600px; margin: 0 auto;">
    <h2 style="font-size: 22px; margin-bottom: 4px;">Monthly Report — ${org.name}</h2>
    <p style="color: #6b7280;">${firstOfMonth.toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
    <table style="width: 100%; border-collapse: collapse;">
      <tr><td style="padding: 8px 0; font-weight: 600;">Total Calls</td><td style="text-align: right;">${calls.length}</td></tr>
      <tr><td style="padding: 8px 0; color: #6b7280;">Outbound Calls</td><td style="text-align: right;">${outboundCalls}</td></tr>
      <tr><td style="padding: 8px 0; color: #6b7280;">Inbound Calls</td><td style="text-align: right;">${inboundCalls}</td></tr>
      <tr><td style="padding: 8px 0; color: #059669;">Completed Calls</td><td style="text-align: right;">${completedCalls}</td></tr>
      <tr><td style="padding: 8px 0; color: #dc2626;">Failed Calls</td><td style="text-align: right;">${failedCalls}</td></tr>
      <tr><td style="padding: 8px 0; color: #dc2626;">Emergencies Detected</td><td style="text-align: right;">${emergencyCalls}</td></tr>
      <tr><td style="padding: 8px 0;">Avg AI Severity</td><td style="text-align: right;">${avgSeverity}</td></tr>
      <tr><td colspan="2" style="padding: 4px 0;"><hr style="border: none; border-top: 1px solid #e5e7eb;" /></td></tr>
      <tr><td style="padding: 8px 0; font-weight: 600;">Total Appointments</td><td style="text-align: right;">${totalAppointments}</td></tr>
      <tr><td style="padding: 8px 0; color: #059669;">Completed</td><td style="text-align: right;">${completedAppts}</td></tr>
      <tr><td style="padding: 8px 0; color: #dc2626;">No-Shows</td><td style="text-align: right;">${noShows}</td></tr>
      <tr><td style="padding: 8px 0; color: #f59e0b;">Cancelled</td><td style="text-align: right;">${cancellations}</td></tr>
      <tr><td colspan="2" style="padding: 4px 0;"><hr style="border: none; border-top: 1px solid #e5e7eb;" /></td></tr>
      <tr><td style="padding: 8px 0;">Active Patients</td><td style="text-align: right;">${patientCount}</td></tr>
      <tr><td style="padding: 8px 0;">Active Staff</td><td style="text-align: right;">${userCount}</td></tr>
    </table>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
    <p style="color: #9ca3af; font-size: 12px;">Generated by Oriveo on ${now.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
  </div>
</body>
</html>`;

      if (owner.email) {
        await sendEmail({
          to: owner.email,
          subject: `Monthly Report — ${org.name} (${firstOfMonth.toLocaleDateString("en-US", { month: "long", year: "numeric" })})`,
          html,
        });
      }
    }

    logger.info("MonthlyReport", `Generated reports for ${organizations.length} organizations`);
  } catch (err) {
    logger.error("MonthlyReport", err.message);
  }
}

export function startMonthlyReportScheduler() {
  const run = () => {
    const now = new Date();
    if (now.getDate() === 1 && now.getHours() === 9 && now.getMinutes() === 0) {
      generateMonthlyReports();
    }
  };
  run();
  intervalHandle = setInterval(run, 60 * 1000);
}

export function stopMonthlyReportScheduler() {
  if (intervalHandle) {
    clearInterval(intervalHandle);
    intervalHandle = null;
  }
}
